# -*- coding: utf-8 -*-
"""html_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhT1EimlcJLh7-HClw5Au75rzyeuCtMY
"""

# src/report/html_generator.py

"""
HTML REPORT GENERATOR
─────────────────────
Generates a beautiful, branded HTML report with:
- Header with title, period, domain
- KPI dashboard cards
- AI-generated narrative sections
- Embedded interactive Plotly charts
- Professional styling
- Footer with metadata

The HTML file is self-contained — can be opened in any browser,
emailed to stakeholders, or printed to PDF.
"""

from jinja2 import Template
from datetime import datetime
from typing import Dict, List, Optional
import plotly.io as pio
from src.utils.logger import logger


class HTMLReportGenerator:
    """
    Generates a complete HTML report.

    Usage:
        generator = HTMLReportGenerator()
        html = generator.generate(
            title="Monthly Report",
            period="January 2025",
            domain_name="Sales & Revenue",
            domain_icon="💰",
            kpis=kpi_results,
            narrative_sections=sections,
            chart_figures=chart_figures,
            quality_score=quality,
            llm_stats=stats,
        )
    """

    TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.7;
            color: #2c3e50;
            background: #f5f6fa;
        }

        .container {
            max-width: 960px;
            margin: 0 auto;
            background: white;
            box-shadow: 0 0 30px rgba(0,0,0,0.08);
        }

        /* ── HEADER ────────────────────── */
        .header {
            background: linear-gradient(135deg, #1a237e 0%, #283593 50%, #3949ab 100%);
            color: white;
            padding: 50px 40px;
            text-align: center;
            position: relative;
            overflow: hidden;
        }

        .header::before {
            content: '';
            position: absolute;
            top: -50%;
            left: -50%;
            width: 200%;
            height: 200%;
            background: radial-gradient(circle, rgba(255,255,255,0.05) 0%, transparent 70%);
        }

        .header h1 {
            font-size: 32px;
            font-weight: 700;
            margin-bottom: 8px;
            position: relative;
        }

        .header .subtitle {
            font-size: 16px;
            opacity: 0.85;
            position: relative;
        }

        .header .domain-badge {
            display: inline-block;
            background: rgba(255,255,255,0.15);
            padding: 6px 18px;
            border-radius: 20px;
            margin-top: 12px;
            font-size: 14px;
            position: relative;
        }

        /* ── KPI CARDS ─────────────────── */
        .kpi-section {
            padding: 30px 40px;
            background: #f8f9fa;
            border-bottom: 1px solid #e0e0e0;
        }

        .kpi-section h2 {
            font-size: 18px;
            color: #1a237e;
            margin-bottom: 16px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .kpi-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 16px;
        }

        .kpi-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
            box-shadow: 0 2px 10px rgba(0,0,0,0.06);
            border-top: 3px solid #1a237e;
            transition: transform 0.2s;
        }

        .kpi-card:hover {
            transform: translateY(-2px);
        }

        .kpi-icon {
            font-size: 24px;
            margin-bottom: 6px;
        }

        .kpi-value {
            font-size: 26px;
            font-weight: 700;
            color: #1a237e;
            margin-bottom: 2px;
        }

        .kpi-label {
            font-size: 11px;
            color: #888;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        /* ── CONTENT ───────────────────── */
        .content {
            padding: 40px;
        }

        .section {
            margin-bottom: 35px;
            padding-bottom: 25px;
            border-bottom: 1px solid #eee;
        }

        .section:last-child {
            border-bottom: none;
        }

        .section h2 {
            color: #1a237e;
            font-size: 22px;
            margin-bottom: 16px;
            padding-bottom: 8px;
            border-bottom: 3px solid #4fc3f7;
            display: inline-block;
        }

        .section-content {
            font-size: 15px;
            color: #34495e;
        }

        .section-content p {
            margin-bottom: 12px;
        }

        .section-content strong {
            color: #1a237e;
        }

        .section-content ul, .section-content ol {
            margin: 10px 0 10px 20px;
        }

        .section-content li {
            margin-bottom: 6px;
        }

        .section-content h3 {
            color: #283593;
            font-size: 17px;
            margin: 18px 0 10px 0;
        }

        /* ── CHARTS ────────────────────── */
        .charts-section {
            padding: 30px 40px;
            background: #fafbfc;
        }

        .charts-section h2 {
            color: #1a237e;
            font-size: 22px;
            margin-bottom: 20px;
            padding-bottom: 8px;
            border-bottom: 3px solid #4fc3f7;
            display: inline-block;
        }

        .chart-container {
            margin: 20px 0;
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
            padding: 10px;
        }

        .chart-caption {
            text-align: center;
            font-size: 12px;
            color: #888;
            padding: 8px;
            font-style: italic;
        }

        /* ── QUALITY BADGE ─────────────── */
        .quality-section {
            padding: 20px 40px;
            background: #f0f4ff;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 15px;
        }

        .quality-badge {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .quality-score {
            font-size: 36px;
            font-weight: 700;
            color: #1a237e;
        }

        .quality-label {
            font-size: 12px;
            color: #666;
        }

        .quality-meta {
            font-size: 12px;
            color: #888;
            text-align: right;
        }

        /* ── FOOTER ────────────────────── */
        .footer {
            background: #1a237e;
            color: rgba(255,255,255,0.7);
            padding: 25px 40px;
            text-align: center;
            font-size: 12px;
        }

        .footer a {
            color: #4fc3f7;
            text-decoration: none;
        }

        .footer .disclaimer {
            margin-top: 8px;
            font-size: 11px;
            opacity: 0.6;
        }

        /* ── RESPONSIVE ────────────────── */
        @media (max-width: 768px) {
            .header { padding: 30px 20px; }
            .header h1 { font-size: 24px; }
            .content { padding: 20px; }
            .kpi-section { padding: 20px; }
            .kpi-grid { grid-template-columns: repeat(2, 1fr); }
            .charts-section { padding: 20px; }
            .quality-section { flex-direction: column; text-align: center; }
        }

        /* ── PRINT ─────────────────────── */
        @media print {
            body { background: white; }
            .container { box-shadow: none; }
            .chart-container { break-inside: avoid; }
            .section { break-inside: avoid; }
        }
    </style>
</head>
<body>
    <div class="container">

        <!-- HEADER -->
        <div class="header">
            <h1>{{ title }}</h1>
            <div class="subtitle">
                Report Period: {{ period }} &nbsp;|&nbsp; Generated: {{ generated_date }}
            </div>
            <div class="domain-badge">
                {{ domain_icon }} {{ domain_name }}
            </div>
        </div>

        <!-- KPI CARDS -->
        {% if kpi_cards %}
        <div class="kpi-section">
            <h2>📊 Key Metrics</h2>
            <div class="kpi-grid">
                {% for kpi in kpi_cards %}
                <div class="kpi-card">
                    <div class="kpi-icon">{{ kpi.icon }}</div>
                    <div class="kpi-value">{{ kpi.value }}</div>
                    <div class="kpi-label">{{ kpi.label }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <!-- NARRATIVE SECTIONS -->
        <div class="content">
            {% for section in sections %}
            <div class="section">
                <h2>{{ section.title }}</h2>
                <div class="section-content">
                    {{ section.content }}
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- CHARTS -->
        {% if charts %}
        <div class="charts-section">
            <h2>📈 Visualizations</h2>
            {% for chart in charts %}
            <div class="chart-container">
                {{ chart.html }}
                <div class="chart-caption">💡 {{ chart.reason }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- QUALITY SCORE -->
        {% if quality %}
        <div class="quality-section">
            <div class="quality-badge">
                <div class="quality-score">{{ quality.emoji }} {{ quality.score }}/100</div>
                <div>
                    <div style="font-weight:600; color:#1a237e;">Report Quality</div>
                    <div class="quality-label">{{ quality.rating }}</div>
                </div>
            </div>
            <div class="quality-meta">
                <div>Provider: {{ llm_provider }}</div>
                <div>Cost: {{ llm_cost }}</div>
                <div>Tokens: {{ llm_tokens }}</div>
            </div>
        </div>
        {% endif %}

        <!-- FOOTER -->
        <div class="footer">
            <div>
                Generated by <strong>AI Business Report Generator</strong>
                &nbsp;|&nbsp; {{ generated_date }}
            </div>
            <div class="disclaimer">
                This report was auto-generated using AI analysis.
                Please verify critical data points before making business decisions.
            </div>
        </div>

    </div>
</body>
</html>"""


    def generate(self,
                 title: str,
                 period: str,
                 domain_name: str = "General",
                 domain_icon: str = "📊",
                 kpis: Optional[Dict] = None,
                 narrative_sections: Optional[Dict] = None,
                 chart_figures: Optional[List] = None,
                 quality_score: Optional[Dict] = None,
                 llm_stats: Optional[Dict] = None) -> str:
        """
        Generate complete HTML report.

        Parameters:
        -----------
        title : str - Report title
        period : str - Report period
        domain_name : str - Domain display name
        domain_icon : str - Domain emoji
        kpis : Dict - KPI results from SmartKPICalculator
        narrative_sections : Dict - Generated text sections
        chart_figures : List - Chart figures from ChartBuilder
        quality_score : Dict - Quality assessment results
        llm_stats : Dict - LLM session stats

        Returns:
        --------
        str : Complete HTML document
        """

        logger.info("Generating HTML report...")

        # ── Format KPI cards ───────────────────────────
        kpi_cards = self._format_kpis(kpis) if kpis else []

        # ── Format narrative sections ──────────────────
        sections = self._format_sections(narrative_sections) if narrative_sections else []

        # ── Convert charts to HTML ─────────────────────
        charts = self._format_charts(chart_figures) if chart_figures else []

        # ── Quality info ───────────────────────────────
        quality = None
        if quality_score:
            quality = {
                "score": quality_score.get("overall_score", 0),
                "rating": quality_score.get("rating", "N/A"),
                "emoji": quality_score.get("emoji", "📊"),
            }

        # ── LLM info ──────────────────────────────────
        llm_provider = "N/A"
        llm_cost = "N/A"
        llm_tokens = "N/A"
        if llm_stats:
            llm_provider = llm_stats.get("provider", "N/A")
            llm_cost = llm_stats.get("total_cost_formatted", "FREE")
            total_tokens = (
                llm_stats.get("total_input_tokens", 0) +
                llm_stats.get("total_output_tokens", 0)
            )
            llm_tokens = f"{total_tokens:,}"

        # ── Render template ───────────────────────────
        template = Template(self.TEMPLATE)
        html = template.render(
            title=title,
            period=period,
            generated_date=datetime.now().strftime("%B %d, %Y %H:%M"),
            domain_name=domain_name,
            domain_icon=domain_icon,
            kpi_cards=kpi_cards,
            sections=sections,
            charts=charts,
            quality=quality,
            llm_provider=llm_provider,
            llm_cost=llm_cost,
            llm_tokens=llm_tokens,
        )

        logger.info("HTML report generated successfully")
        return html


    def _format_kpis(self, kpis: Dict) -> List[Dict]:
        """Format KPIs for display cards."""

        cards = []
        kpi_data = kpis.get("kpis", {})
        kpi_defs = kpis.get("kpi_definitions", [])

        for kpi_def in kpi_defs:
            key = kpi_def["key"]
            if key in kpi_data:
                value = kpi_data[key]
                try:
                    formatted = kpi_def["format"].format(value)
                except (ValueError, KeyError):
                    formatted = str(value)

                cards.append({
                    "icon": kpi_def.get("icon", "📊"),
                    "value": formatted,
                    "label": kpi_def["name"],
                })

        return cards[:8]


    def _format_sections(self, sections: Dict) -> List[Dict]:
        """Format narrative sections for HTML."""

        section_titles = {
            "executive_summary": "📋 Executive Summary",
            "kpi_analysis": "📊 KPI Analysis",
            "trend_analysis": "📈 Trend Analysis",
            "anomalies_alerts": "⚠️ Key Observations & Alerts",
            "recommendations": "🎯 Recommendations",
            "full_report": "📄 Full Report",
        }

        formatted = []

        for key, content in sections.items():
            if not content or content.startswith("*[Error"):
                continue

            title = section_titles.get(key, key.replace('_', ' ').title())
            html_content = self._markdown_to_html(content)

            formatted.append({
                "title": title,
                "content": html_content,
            })

        return formatted


    def _format_charts(self, chart_figures: List) -> List[Dict]:
        """Convert Plotly figures to embeddable HTML."""

        charts = []

        for chart_data in chart_figures:
            try:
                fig = chart_data["figure"]
                spec = chart_data["spec"]

                chart_html = pio.to_html(
                    fig,
                    full_html=False,
                    include_plotlyjs='cdn',
                    config={
                        'displayModeBar': True,
                        'displaylogo': False,
                        'modeBarButtonsToRemove': [
                            'sendDataToCloud', 'lasso2d', 'select2d'
                        ],
                    }
                )

                charts.append({
                    "html": chart_html,
                    "reason": spec.reason,
                })

            except Exception as e:
                logger.warning(f"Failed to convert chart to HTML: {e}")

        return charts


    def _markdown_to_html(self, text: str) -> str:
        """Convert markdown to basic HTML."""

        import re

        html = text

        # Bold
        html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)

        # Italic
        html = re.sub(r'\*(.*?)\*', r'<em>\1</em>', html)

        # Headers
        html = re.sub(
            r'^#### (.*?)$', r'<h4>\1</h4>', html, flags=re.MULTILINE
        )
        html = re.sub(
            r'^### (.*?)$', r'<h3>\1</h3>', html, flags=re.MULTILINE
        )
        html = re.sub(
            r'^## (.*?)$', r'<h3>\1</h3>', html, flags=re.MULTILINE
        )

        # Numbered lists
        html = re.sub(
            r'^\d+\.\s+(.*?)$', r'<li>\1</li>', html, flags=re.MULTILINE
        )

        # Bullet points
        html = re.sub(
            r'^[-•]\s+(.*?)$', r'<li>\1</li>', html, flags=re.MULTILINE
        )

        # Wrap consecutive <li> in <ul>
        html = re.sub(
            r'((?:<li>.*?</li>\n?)+)',
            r'<ul>\1</ul>',
            html
        )

        # Paragraphs
        paragraphs = html.split('\n\n')
        processed = []
        for p in paragraphs:
            p = p.strip()
            if not p:
                continue
            if p.startswith('<'):
                processed.append(p)
            else:
                processed.append(f'<p>{p}</p>')

        html = '\n'.join(processed)

        # Clean up line breaks within paragraphs
        html = html.replace('\n', ' ')
        html = re.sub(r'\s+', ' ', html)

        return html