# -*- coding: utf-8 -*-
"""quality_scorer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/narrative/quality_scorer.py

"""
REPORT QUALITY SCORER
─────────────────────
Scores the generated report on multiple dimensions.

WHY?
1. Helps you iterate on prompts (see what's working)
2. Shows recruiters you think about OUTPUT QUALITY
3. Can flag low-quality sections for regeneration
4. Adds a "Report Quality Score" to the final output
"""

import re
from typing import Dict, List
from src.utils.logger import logger


class ReportQualityScorer:
    """
    Scores generated report sections on multiple criteria.

    Criteria:
    1. Data Grounding — does it reference specific numbers?
    2. Structure — does it use headers, bullets, formatting?
    3. Actionability — does it include recommendations/next steps?
    4. Conciseness — is it within word limits?
    5. Completeness — does it cover all required topics?
    """

    def score_report(self, sections: Dict[str, str],
                     analysis_bundle: Dict) -> Dict:
        """
        Score the entire report.

        Returns:
        --------
        Dict with:
            - overall_score: 0-100
            - section_scores: {section_name: {criteria: score}}
            - suggestions: improvement suggestions
        """

        logger.info("Scoring report quality...")

        section_scores = {}
        all_scores = []

        for section_name, content in sections.items():
            scores = self._score_section(section_name, content, analysis_bundle)
            section_scores[section_name] = scores
            all_scores.append(scores["total_score"])

        overall_score = round(sum(all_scores) / len(all_scores), 1) if all_scores else 0

        # Generate improvement suggestions
        suggestions = self._generate_suggestions(section_scores)

        # Quality rating
        if overall_score >= 90:
            rating = "Excellent"
            emoji = "🏆"
        elif overall_score >= 75:
            rating = "Good"
            emoji = "✅"
        elif overall_score >= 60:
            rating = "Fair"
            emoji = "⚠️"
        else:
            rating = "Needs Improvement"
            emoji = "🔴"

        result = {
            "overall_score": overall_score,
            "rating": rating,
            "emoji": emoji,
            "section_scores": section_scores,
            "suggestions": suggestions,
        }

        logger.info(f"Report quality: {overall_score}/100 ({rating})")
        return result


    def _score_section(self, section_name: str, content: str,
                       bundle: Dict) -> Dict:
        """Score a single section"""

        scores = {}

        # 1. Data Grounding (0-25)
        scores["data_grounding"] = self._score_data_grounding(content, bundle)

        # 2. Structure (0-25)
        scores["structure"] = self._score_structure(content)

        # 3. Actionability (0-25)
        scores["actionability"] = self._score_actionability(content, section_name)

        # 4. Conciseness (0-25)
        scores["conciseness"] = self._score_conciseness(content, section_name)

        # Total
        scores["total_score"] = round(sum([
            scores["data_grounding"],
            scores["structure"],
            scores["actionability"],
            scores["conciseness"],
        ]), 1)

        return scores


    def _score_data_grounding(self, content: str, bundle: Dict) -> float:
        """Does the section reference actual numbers from the data?"""

        score = 0

        # Count numbers in text
        numbers = re.findall(r'\d+[\d,.]*\d+|\d+', content)
        number_count = len(numbers)

        # Count percentage mentions
        percentages = re.findall(r'\d+\.?\d*\s*%', content)
        pct_count = len(percentages)

        # Count dollar/currency mentions
        currency = re.findall(r'\$[\d,.]+', content)
        currency_count = len(currency)

        total_data_refs = number_count + pct_count + currency_count

        if total_data_refs >= 8:
            score = 25
        elif total_data_refs >= 5:
            score = 20
        elif total_data_refs >= 3:
            score = 15
        elif total_data_refs >= 1:
            score = 10
        else:
            score = 5

        return score


    def _score_structure(self, content: str) -> float:
        """Is the content well-structured with formatting?"""

        score = 0

        # Check for bold text
        bold_count = len(re.findall(r'\*\*.*?\*\*', content))
        if bold_count >= 3:
            score += 8
        elif bold_count >= 1:
            score += 4

        # Check for bullet points
        bullet_count = len(re.findall(r'^[-•*]\s', content, re.MULTILINE))
        numbered_count = len(re.findall(r'^\d+[.)]\s', content, re.MULTILINE))
        list_items = bullet_count + numbered_count

        if list_items >= 3:
            score += 8
        elif list_items >= 1:
            score += 4

        # Check for headers
        headers = len(re.findall(r'^#{1,4}\s', content, re.MULTILINE))
        if headers >= 2:
            score += 5
        elif headers >= 1:
            score += 3

        # Check for paragraphs (not just one blob)
        paragraphs = len([p for p in content.split('\n\n') if p.strip()])
        if paragraphs >= 3:
            score += 4
        elif paragraphs >= 2:
            score += 2

        return min(score, 25)


    def _score_actionability(self, content: str,
                              section_name: str) -> float:
        """Does it include actionable insights?"""

        score = 0
        content_lower = content.lower()

        # Action words
        action_words = [
            'recommend', 'suggest', 'consider', 'should', 'action',
            'investigate', 'focus', 'prioritize', 'implement',
            'improve', 'optimize', 'monitor', 'track', 'address',
            'increase', 'decrease', 'reduce', 'expand', 'target',
            'opportunity', 'risk', 'concern', 'attention',
        ]

        action_count = sum(
            1 for word in action_words if word in content_lower
        )

        if action_count >= 5:
            score += 15
        elif action_count >= 3:
            score += 10
        elif action_count >= 1:
            score += 5

        # Forward-looking language
        forward_words = [
            'going forward', 'next steps', 'outlook', 'forecast',
            'expect', 'anticipate', 'plan', 'strategy', 'future',
            'trajectory', 'if this continues', 'on track',
        ]

        forward_count = sum(
            1 for word in forward_words if word in content_lower
        )

        if forward_count >= 2:
            score += 10
        elif forward_count >= 1:
            score += 5

        return min(score, 25)


    def _score_conciseness(self, content: str,
                            section_name: str) -> float:
        """Is the content appropriately sized?"""

        word_count = len(content.split())

        # Ideal word counts per section
        ideal_ranges = {
            "executive_summary": (100, 250),
            "kpi_analysis": (150, 350),
            "trend_analysis": (200, 400),
            "anomalies_alerts": (100, 300),
            "recommendations": (200, 400),
        }

        min_words, max_words = ideal_ranges.get(
            section_name, (100, 400)
        )

        if min_words <= word_count <= max_words:
            return 25        # perfect length
        elif word_count < min_words:
            # Too short
            ratio = word_count / min_words
            return max(5, round(25 * ratio))
        else:
            # Too long
            ratio = max_words / word_count
            return max(10, round(25 * ratio))


    def _generate_suggestions(self, section_scores: Dict) -> List[str]:
        """Generate improvement suggestions"""

        suggestions = []

        for section, scores in section_scores.items():
            section_display = section.replace('_', ' ').title()

            if scores["data_grounding"] < 15:
                suggestions.append(
                    f"📊 **{section_display}**: Add more specific data references "
                    f"(numbers, percentages, dollar amounts)"
                )

            if scores["structure"] < 15:
                suggestions.append(
                    f"📋 **{section_display}**: Improve formatting — "
                    f"add headers, bullet points, and bold key metrics"
                )

            if scores["actionability"] < 15:
                suggestions.append(
                    f"🎯 **{section_display}**: Make it more actionable — "
                    f"add recommendations or next steps"
                )

            if scores["conciseness"] < 15:
                word_count = scores.get("word_count", "unknown")
                suggestions.append(
                    f"📏 **{section_display}**: Adjust length — "
                    f"currently may be too short or too long"
                )

        return suggestions