# -*- coding: utf-8 -*-
"""chart_builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/visualization/chart_builder.py

"""
DOMAIN-AWARE CHART BUILDER — V2
────────────────────────────────
Builds Plotly charts from ChartSpec objects WITH domain-aware aggregation.

KEY CHANGE FROM V1:
  V1: Always did .sum() for bar charts
  V2: Uses spec.aggregation → count, sum, mean, median, raw

  Healthcare bar chart: df.groupby("diagnosis")["patient_id"].count()
  HR bar chart:         df.groupby("department")["salary"].mean()
  Sales bar chart:      df.groupby("region")["revenue"].sum()
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from typing import Dict, List, Optional
from src.visualization.chart_recommender import ChartSpec
from src.utils.logger import logger


class ChartBuilder:
    """
    Builds Plotly charts with domain-aware aggregation.

    Usage:
        builder = ChartBuilder()
        figures = builder.build_all(df, chart_specs, trend_results, anomaly_results)
    """

    COLORS = [
        '#1a237e', '#4fc3f7', '#ff7043', '#66bb6a',
        '#ab47bc', '#ffa726', '#ef5350', '#26c6da',
    ]

    POSITIVE_COLOR = '#66bb6a'
    NEGATIVE_COLOR = '#ef5350'
    NEUTRAL_COLOR = '#78909c'
    TREND_COLOR = '#ff7043'
    ANOMALY_COLOR = '#ef5350'


    def build_all(self, df: pd.DataFrame,
                  chart_specs: List[ChartSpec],
                  trend_results: Optional[Dict] = None,
                  anomaly_results: Optional[Dict] = None) -> List[Dict]:
        """Build all charts from specs"""

        figures = []

        for spec in chart_specs:
            try:
                fig = self._build_chart(df, spec, trend_results, anomaly_results)
                if fig is not None:
                    fig = self._apply_styling(fig, spec.title)
                    figures.append({"figure": fig, "spec": spec})
            except Exception as e:
                logger.warning(f"Error building {spec.chart_type} '{spec.title}': {e}")

        logger.info(f"Built {len(figures)} charts successfully")
        return figures


    def _build_chart(self, df, spec, trend_results, anomaly_results):
        """Route to correct builder"""

        builders = {
            "line": self._build_line,
            "bar": self._build_bar,
            "histogram": self._build_histogram,
            "pie": self._build_pie,
            "scatter": self._build_scatter,
            "box": self._build_box,
            "grouped_bar": self._build_grouped_bar,
            "growth_bar": self._build_growth_bar,
            "seasonal_bar": self._build_seasonal_bar,
            "anomaly_scatter": self._build_anomaly,
        }

        func = builders.get(spec.chart_type)
        if func is None:
            logger.warning(f"Unknown chart type: {spec.chart_type}")
            return None

        if spec.chart_type in ["line", "growth_bar", "seasonal_bar"]:
            return func(df, spec, trend_results)
        elif spec.chart_type == "anomaly_scatter":
            return func(df, spec, anomaly_results)
        else:
            return func(df, spec)


    # ═══════════════════════════════════════════════════════
    # AGGREGATION HELPER (THE KEY CHANGE)
    # ═══════════════════════════════════════════════════════

    def _aggregate(self, df: pd.DataFrame, group_col: str,
                   value_col: str, aggregation: str,
                   max_categories: int = 15) -> pd.DataFrame:
        """
        Aggregate data based on chart spec's aggregation type.

        This is THE CORE FIX:
        - "count" → df.groupby(x)[y].count()  (for healthcare patients)
        - "sum"   → df.groupby(x)[y].sum()    (for sales revenue)
        - "mean"  → df.groupby(x)[y].mean()   (for HR salary)
        """

        clean_df = df[[group_col, value_col]].dropna()

        if aggregation == "count":
            agg_series = clean_df.groupby(group_col)[value_col].count()
        elif aggregation == "sum":
            agg_series = clean_df.groupby(group_col)[value_col].sum()
        elif aggregation == "mean":
            agg_series = clean_df.groupby(group_col)[value_col].mean()
        elif aggregation == "median":
            agg_series = clean_df.groupby(group_col)[value_col].median()
        else:
            agg_series = clean_df.groupby(group_col)[value_col].sum()

        agg_series = agg_series.sort_values(ascending=False)
        agg_df = agg_series.head(max_categories).reset_index()
        agg_df.columns = ['category', 'value']

        return agg_df


    def _get_y_label(self, spec: ChartSpec) -> str:
        """Generate appropriate y-axis label based on aggregation"""

        col_name = (spec.y or spec.values or "Value").replace('_', ' ').title()

        prefix_map = {
            "count": "Count of",
            "sum": "Total",
            "mean": "Average",
            "median": "Median",
            "raw": "",
        }

        prefix = prefix_map.get(spec.aggregation, "")

        if spec.aggregation == "count":
            return f"Count"
        elif prefix:
            return f"{prefix} {col_name}"
        else:
            return col_name


    # ═══════════════════════════════════════════════════════
    # CHART BUILDERS
    # ═══════════════════════════════════════════════════════

    def _build_line(self, df, spec, trend_results):
        """Time series line chart with moving average"""

        temp = df[[spec.x, spec.y]].copy()
        temp[spec.x] = pd.to_datetime(temp[spec.x], errors='coerce')
        temp = temp.dropna()

        agg = temp.set_index(spec.x)[spec.y].resample('M').sum().reset_index()
        agg.columns = ['date', 'value']

        fig = go.Figure()

        # Main line
        fig.add_trace(go.Scatter(
            x=agg['date'], y=agg['value'],
            mode='lines+markers',
            name=spec.y.replace('_', ' ').title(),
            line=dict(color=self.COLORS[0], width=2.5),
            marker=dict(size=6),
            hovertemplate='%{x|%b %Y}<br>%{y:,.0f}<extra></extra>',
        ))

        # Moving average
        if len(agg) >= 3:
            ma = agg['value'].rolling(3, min_periods=1).mean()
            fig.add_trace(go.Scatter(
                x=agg['date'], y=ma,
                mode='lines', name='3-Period MA',
                line=dict(color=self.TREND_COLOR, width=1.5, dash='dash'),
                opacity=0.7,
            ))

        # Peak annotation
        peak_idx = agg['value'].idxmax()
        fig.add_annotation(
            x=agg.loc[peak_idx, 'date'], y=agg.loc[peak_idx, 'value'],
            text=f"Peak: {agg.loc[peak_idx, 'value']:,.0f}",
            showarrow=True, arrowhead=2, arrowcolor=self.POSITIVE_COLOR,
            font=dict(size=10, color=self.POSITIVE_COLOR), ax=0, ay=-30,
        )

        fig.update_yaxes(title_text=self._get_y_label(spec))
        return fig


    def _build_bar(self, df, spec):
        """Bar chart with domain-aware aggregation"""

        agg_df = self._aggregate(
            df, spec.x, spec.y, spec.aggregation, spec.max_categories
        )

        # Color top 3 differently
        colors = [
            self.COLORS[0] if i < 3 else self.NEUTRAL_COLOR
            for i in range(len(agg_df))
        ]

        # Format text based on aggregation
        if spec.aggregation in ["mean", "median"]:
            text_vals = agg_df['value'].apply(lambda x: f'{x:,.2f}')
        else:
            text_vals = agg_df['value'].apply(lambda x: f'{x:,.0f}')

        fig = go.Figure(go.Bar(
            x=agg_df['category'], y=agg_df['value'],
            marker_color=colors,
            text=text_vals, textposition='outside',
            hovertemplate='%{x}<br>%{y:,.2f}<extra></extra>',
        ))

        fig.update_yaxes(title_text=self._get_y_label(spec))
        return fig


    def _build_histogram(self, df, spec):
        """Histogram for distribution analysis"""

        fig = px.histogram(
            df.dropna(subset=[spec.x]), x=spec.x,
            nbins=30,
            color_discrete_sequence=[self.COLORS[0]],
            marginal="box", opacity=0.8,
        )

        # Mean and median lines
        col_data = df[spec.x].dropna()
        mean_val = col_data.mean()
        median_val = col_data.median()

        fig.add_vline(
            x=mean_val, line_dash="dash", line_color=self.TREND_COLOR,
            annotation_text=f"Mean: {mean_val:,.1f}",
            annotation_position="top right",
        )
        fig.add_vline(
            x=median_val, line_dash="dot", line_color=self.POSITIVE_COLOR,
            annotation_text=f"Median: {median_val:,.1f}",
            annotation_position="top left",
        )

        fig.update_xaxes(title_text=spec.x.replace('_', ' ').title())
        fig.update_yaxes(title_text="Count")
        return fig


    def _build_pie(self, df, spec):
        """Donut chart for composition"""

        agg_df = self._aggregate(
            df, spec.labels, spec.values, spec.aggregation, 8
        )

        fig = go.Figure(go.Pie(
            labels=agg_df['category'], values=agg_df['value'],
            hole=0.4,
            marker=dict(colors=self.COLORS[:len(agg_df)]),
            textinfo='percent+label', textposition='inside',
            hovertemplate='%{label}<br>Value: %{value:,.0f}<br>%{percent}<extra></extra>',
        ))

        total = agg_df['value'].sum()
        label = "Total" if spec.aggregation != "count" else "Count"
        fmt = f"{total:,.0f}"

        fig.add_annotation(
            text=f"{label}<br>{fmt}",
            x=0.5, y=0.5,
            font=dict(size=14, color=self.COLORS[0]), showarrow=False,
        )

        return fig


    def _build_scatter(self, df, spec):
        """Scatter plot with optional color and trendline"""

        plot_df = df[[spec.x, spec.y]].dropna()

        kwargs = {
            "x": spec.x, "y": spec.y,
            "opacity": 0.6, "trendline": "ols",
            "color_discrete_sequence": self.COLORS,
        }

        if spec.color and spec.color in df.columns:
            plot_df = df[[spec.x, spec.y, spec.color]].dropna()
            kwargs["color"] = spec.color

        fig = px.scatter(plot_df, **kwargs)

        fig.update_xaxes(title_text=spec.x.replace('_', ' ').title())
        fig.update_yaxes(title_text=spec.y.replace('_', ' ').title())
        return fig


    def _build_box(self, df, spec):
        """Box plot for distribution comparison"""

        plot_df = df[[spec.x, spec.y]].dropna()

        # Limit categories
        top_cats = plot_df[spec.x].value_counts().head(spec.max_categories).index
        plot_df = plot_df[plot_df[spec.x].isin(top_cats)]

        fig = px.box(
            plot_df, x=spec.x, y=spec.y,
            color=spec.x,
            color_discrete_sequence=self.COLORS,
            points="outliers",
        )

        fig.update_xaxes(title_text=spec.x.replace('_', ' ').title())
        fig.update_yaxes(title_text=spec.y.replace('_', ' ').title())
        fig.update_layout(showlegend=False)
        return fig


    def _build_grouped_bar(self, df, spec):
        """Grouped bar chart with domain-aware aggregation"""

        if spec.color is None or spec.color not in df.columns:
            return self._build_bar(df, spec)

        cols_needed = [spec.x, spec.y]
        if spec.color:
            cols_needed.append(spec.color)
        clean_df = df[cols_needed].dropna()

        # Aggregate
        if spec.aggregation == "count":
            agg_df = clean_df.groupby([spec.x, spec.color])[spec.y].count().reset_index()
        elif spec.aggregation == "mean":
            agg_df = clean_df.groupby([spec.x, spec.color])[spec.y].mean().reset_index()
        else:
            agg_df = clean_df.groupby([spec.x, spec.color])[spec.y].sum().reset_index()

        # Limit categories
        top_x = clean_df[spec.x].value_counts().head(spec.max_categories).index
        agg_df = agg_df[agg_df[spec.x].isin(top_x)]

        fig = px.bar(
            agg_df, x=spec.x, y=spec.y, color=spec.color,
            barmode='group',
            color_discrete_sequence=self.COLORS,
            text=spec.y,
        )

        fig.update_traces(texttemplate='%{text:.2s}', textposition='outside')
        fig.update_yaxes(title_text=self._get_y_label(spec))
        return fig


    def _build_growth_bar(self, df, spec, trend_results):
        """Growth rate bar chart (green=positive, red=negative)"""

        temp = df[[spec.x, spec.y]].copy()
        temp[spec.x] = pd.to_datetime(temp[spec.x], errors='coerce')
        temp = temp.dropna()

        monthly = temp.set_index(spec.x)[spec.y].resample('M').sum()
        pct = monthly.pct_change().dropna() * 100

        if len(pct) == 0:
            return None

        colors = [
            self.POSITIVE_COLOR if v >= 0 else self.NEGATIVE_COLOR
            for v in pct.values
        ]

        fig = go.Figure(go.Bar(
            x=pct.index, y=pct.values.round(1),
            marker_color=colors,
            text=[f"{v:+.1f}%" for v in pct.values],
            textposition='outside',
            hovertemplate='%{x|%b %Y}<br>Growth: %{y:+.1f}%<extra></extra>',
        ))

        fig.add_hline(y=0, line_color="black", line_width=1)

        avg = pct.mean()
        fig.add_hline(
            y=avg, line_dash="dash", line_color=self.COLORS[1],
            annotation_text=f"Avg: {avg:+.1f}%",
            annotation_position="top right",
        )

        fig.update_yaxes(title_text="Growth Rate (%)")
        return fig


    def _build_seasonal_bar(self, df, spec, trend_results):
        """Monthly seasonality bar chart"""

        temp = df[[spec.x, spec.y]].copy()
        temp[spec.x] = pd.to_datetime(temp[spec.x], errors='coerce')
        temp = temp.dropna()

        temp['month'] = temp[spec.x].dt.month
        monthly_avg = temp.groupby('month')[spec.y].mean()

        month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                       'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

        available = [month_names[int(m) - 1] for m in monthly_avg.index if int(m) <= 12]
        peak = monthly_avg.idxmax()

        colors = [
            self.COLORS[0] if m == peak else self.COLORS[1]
            for m in monthly_avg.index
        ]

        fig = go.Figure(go.Bar(
            x=available, y=monthly_avg.values.round(0),
            marker_color=colors,
            text=monthly_avg.values.round(0).astype(int),
            textposition='outside',
        ))

        overall = monthly_avg.mean()
        fig.add_hline(
            y=overall, line_dash="dash", line_color=self.TREND_COLOR,
            annotation_text=f"Avg: {overall:,.0f}",
        )

        fig.update_xaxes(title_text="Month")
        fig.update_yaxes(title_text=self._get_y_label(spec))
        return fig


    def _build_anomaly(self, df, spec, anomaly_results):
        """Scatter highlighting anomalies"""

        temp = df[[spec.x, spec.y]].copy()
        temp[spec.x] = pd.to_datetime(temp[spec.x], errors='coerce')
        temp = temp.dropna()

        series = temp[spec.y]
        Q1, Q3 = series.quantile(0.25), series.quantile(0.75)
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR

        temp['is_anomaly'] = (series < lower) | (series > upper)

        fig = go.Figure()

        normal = temp[~temp['is_anomaly']]
        fig.add_trace(go.Scatter(
            x=normal[spec.x], y=normal[spec.y],
            mode='markers', name='Normal',
            marker=dict(color=self.COLORS[1], size=5, opacity=0.5),
        ))

        anomalies = temp[temp['is_anomaly']]
        fig.add_trace(go.Scatter(
            x=anomalies[spec.x], y=anomalies[spec.y],
            mode='markers', name=f'Anomaly ({len(anomalies)})',
            marker=dict(color=self.ANOMALY_COLOR, size=10, symbol='diamond',
                        line=dict(width=1, color='white')),
        ))

        fig.add_hline(y=upper, line_dash="dash", line_color=self.NEGATIVE_COLOR, opacity=0.5,
                       annotation_text=f"Upper: {upper:,.0f}")
        fig.add_hline(y=lower, line_dash="dash", line_color=self.NEGATIVE_COLOR, opacity=0.5,
                       annotation_text=f"Lower: {lower:,.0f}")

        fig.update_yaxes(title_text=spec.y.replace('_', ' ').title())
        return fig


    # ═══════════════════════════════════════════════════════
    # STYLING
    # ═══════════════════════════════════════════════════════

    def _apply_styling(self, fig, title):
        """Consistent professional styling"""

        fig.update_layout(
            title={
                'text': title,
                'x': 0.5, 'xanchor': 'center',
                'font': dict(size=16, color='#2c3e50',
                             family='Segoe UI, sans-serif'),
            },
            template="plotly_white",
            height=420,
            margin=dict(l=50, r=30, t=60, b=50),
            font=dict(family='Segoe UI, sans-serif', size=12, color='#2c3e50'),
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02,
                xanchor="right", x=1, font=dict(size=10),
            ),
            hoverlabel=dict(bgcolor="white", font_size=12),
            plot_bgcolor='rgba(0,0,0,0)',
        )

        fig.update_xaxes(showgrid=False, showline=True,
                         linewidth=1, linecolor='#e0e0e0')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#f0f0f0',
                         showline=True, linewidth=1, linecolor='#e0e0e0')

        return fig