# -*- coding: utf-8 -*-
"""chart_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/visualization/chart_recommender.py

"""
DOMAIN-AWARE CHART RECOMMENDER — V2
────────────────────────────────────
Now reads chart specifications DIRECTLY from domain_config.py
instead of guessing what charts to show.

BEFORE: Guessed charts based on column types → wrong charts for healthcare
AFTER:  Reads DomainChartSpec list → exact charts per domain

Healthcare: Patient count by diagnosis bar, gender pie, age histogram
HR:         Headcount by dept bar, salary histogram, attrition grouped bar
Sales:      Revenue trend line, revenue by region bar, category pie

Also adds:
- Trend charts (if trend data available)
- Anomaly charts (if anomalies detected)
- Growth rate bars
- Seasonality bars
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional
from dataclasses import dataclass, field
from src.analysis.domain_config import (
    DomainConfig, DomainChartSpec, get_domain_config, SALES_DOMAIN
)
from src.utils.logger import logger


@dataclass
class ChartSpec:
    """Final chart specification passed to ChartBuilder"""
    chart_type: str
    title: str
    x: Optional[str] = None
    y: Optional[str] = None
    color: Optional[str] = None
    labels: Optional[str] = None
    values: Optional[str] = None
    aggregation: str = "sum"
    priority: int = 5
    reason: str = ""
    section: str = "general"
    max_categories: int = 15


class ChartRecommender:
    """
    Recommends charts based on domain configuration.

    Usage:
        recommender = ChartRecommender(
            domain_id="healthcare",
            column_mapping={"patient": "patient_id", "diagnosis": "condition"}
        )
        chart_specs = recommender.recommend(df, trend_results, anomaly_results)
    """

    def __init__(self,
                 domain_id: str = "auto",
                 column_mapping: Optional[Dict[str, str]] = None):

        self.domain_id = domain_id
        self.column_mapping = column_mapping or {}

        self.domain_config = get_domain_config(domain_id)
        if self.domain_config is None:
            self.domain_config = SALES_DOMAIN

        logger.info(
            f"ChartRecommender initialized for: "
            f"{self.domain_config.display_name}"
        )


    def recommend(self,
                  df: pd.DataFrame,
                  trend_results: Optional[Dict] = None,
                  anomaly_results: Optional[Dict] = None,
                  max_charts: int = 8) -> List[ChartSpec]:
        """
        Generate chart recommendations from domain config.

        Steps:
        1. Convert DomainChartSpecs → ChartSpecs (map roles → columns)
        2. Add trend charts if trend data exists
        3. Add anomaly charts if anomalies detected
        4. Filter out charts with missing columns
        5. Sort by priority, limit to max_charts
        """

        logger.info("Generating domain-specific chart recommendations...")

        charts = []

        # ── 1. Domain-defined charts ───────────────────
        for domain_spec in self.domain_config.chart_specs:
            chart = self._convert_domain_spec(df, domain_spec)
            if chart is not None:
                charts.append(chart)

        # ── 2. Trend charts ────────────────────────────
        if trend_results and trend_results.get("available"):
            trend_charts = self._trend_charts(df, trend_results)
            charts.extend(trend_charts)

        # ── 3. Anomaly charts ──────────────────────────
        if anomaly_results and anomaly_results.get("column_anomalies"):
            anomaly_charts = self._anomaly_charts(df, anomaly_results)
            charts.extend(anomaly_charts)

        # ── 4. Deduplicate and sort ────────────────────
        charts = self._deduplicate(charts)
        charts.sort(key=lambda c: c.priority)

        logger.info(f"Recommended {min(len(charts), max_charts)} charts")
        return charts[:max_charts]


    def _convert_domain_spec(self, df: pd.DataFrame,
                              domain_spec: DomainChartSpec) -> Optional[ChartSpec]:
        """
        Convert a DomainChartSpec (uses roles) to a ChartSpec (uses actual columns).

        DomainChartSpec says: x_role="diagnosis", y_role="patient", aggregation="count"
        ChartSpec says:       x="condition", y="patient_id", aggregation="count"
        """

        # Map roles to actual columns
        x_col = self._get_column(domain_spec.x_role)
        y_col = self._get_column(domain_spec.y_role) if domain_spec.y_role else None
        color_col = self._get_column(domain_spec.color_role) if domain_spec.color_role else None

        # x column is required
        if x_col is None or x_col not in df.columns:
            logger.debug(
                f"Skipping chart '{domain_spec.title}': "
                f"no column for role '{domain_spec.x_role}'"
            )
            return None

        # For non-raw aggregations, y column might be needed
        if domain_spec.aggregation not in ["raw", "count"] and y_col is not None:
            if y_col not in df.columns:
                return None

        # For count aggregation, y can be any column (we just count rows)
        if domain_spec.aggregation == "count" and y_col is None:
            # Use x_col as y for counting
            y_col = x_col

        # Validate categorical columns have reasonable cardinality
        if domain_spec.chart_type in ["bar", "pie", "grouped_bar", "box"]:
            if domain_spec.aggregation != "raw":
                n_unique = df[x_col].nunique()
                if n_unique > domain_spec.max_categories or n_unique < 2:
                    logger.debug(
                        f"Skipping chart '{domain_spec.title}': "
                        f"{x_col} has {n_unique} unique values"
                    )
                    return None

        # Validate color column
        if color_col and color_col in df.columns:
            if df[color_col].nunique() > 10 or df[color_col].nunique() < 2:
                color_col = None

        # Handle pie charts specially
        if domain_spec.chart_type == "pie":
            return ChartSpec(
                chart_type="pie",
                title=domain_spec.title,
                labels=x_col,
                values=y_col,
                aggregation=domain_spec.aggregation,
                priority=domain_spec.priority,
                reason=domain_spec.reason,
                section=domain_spec.section,
                max_categories=domain_spec.max_categories,
            )

        return ChartSpec(
            chart_type=domain_spec.chart_type,
            title=domain_spec.title,
            x=x_col,
            y=y_col,
            color=color_col,
            aggregation=domain_spec.aggregation,
            priority=domain_spec.priority,
            reason=domain_spec.reason,
            section=domain_spec.section,
            max_categories=domain_spec.max_categories,
        )


    def _trend_charts(self, df: pd.DataFrame,
                      trend_results: Dict) -> List[ChartSpec]:
        """Add time-based trend charts"""

        charts = []
        config = trend_results.get("config", {})
        date_col = config.get("date_column")
        value_col = config.get("value_column")

        if not date_col or not value_col:
            return charts

        if date_col not in df.columns or value_col not in df.columns:
            return charts

        # Get domain-appropriate label
        vocab = self.domain_config.vocabulary
        metric_name = value_col.replace('_', ' ').title()

        # Line chart already added by domain specs? Check
        existing_line = any(
            s.chart_type == "line"
            for s in self.domain_config.chart_specs
        )

        if not existing_line:
            charts.append(ChartSpec(
                chart_type="line",
                title=f"{metric_name} Over Time",
                x=date_col,
                y=value_col,
                aggregation="sum",
                priority=1,
                reason=f"Track {vocab.primary_metric_name} trajectory",
                section="trends",
            ))

        # Growth rate bar chart
        growth = trend_results.get("growth_analysis", {})
        if growth and growth.get("period_growth_rates"):
            charts.append(ChartSpec(
                chart_type="growth_bar",
                title=f"{metric_name} Growth Rate (%)",
                x=date_col,
                y=value_col,
                aggregation="sum",
                priority=2,
                reason="Period-over-period growth visualization",
                section="trends",
            ))

        # Seasonality bar
        seasonality = trend_results.get("seasonality", {})
        if seasonality.get("detected"):
            charts.append(ChartSpec(
                chart_type="seasonal_bar",
                title=f"Seasonal Pattern — Avg {metric_name} by Month",
                x=date_col,
                y=value_col,
                aggregation="sum",
                priority=6,
                reason="Seasonal pattern detected in data",
                section="trends",
            ))

        return charts


    def _anomaly_charts(self, df: pd.DataFrame,
                        anomaly_results: Dict) -> List[ChartSpec]:
        """Add anomaly highlight charts"""

        charts = []
        date_col = self._find_date_col(df)

        if not date_col:
            return charts

        affected = anomaly_results.get("summary", {}).get("affected_columns", [])

        for col in affected[:1]:
            if col in df.columns:
                charts.append(ChartSpec(
                    chart_type="anomaly_scatter",
                    title=f"⚠️ Anomaly Detection — {col.replace('_', ' ').title()}",
                    x=date_col,
                    y=col,
                    aggregation="raw",
                    priority=3,
                    reason="Highlight detected outliers",
                    section="anomalies",
                ))

        return charts


    def _get_column(self, role: Optional[str]) -> Optional[str]:
        """Get actual column name from role"""
        if role is None:
            return None
        return self.column_mapping.get(role)


    def _find_date_col(self, df: pd.DataFrame) -> Optional[str]:
        """Find datetime column"""
        dt_cols = df.select_dtypes(include=['datetime64']).columns
        return dt_cols[0] if len(dt_cols) > 0 else None


    def _deduplicate(self, charts: List[ChartSpec]) -> List[ChartSpec]:
        """Remove duplicate charts"""
        seen = set()
        unique = []
        for chart in charts:
            key = (chart.chart_type, chart.x, chart.y, chart.labels)
            if key not in seen:
                seen.add(key)
                unique.append(chart)
        return unique