# -*- coding: utf-8 -*-
"""logger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/utils/logger.py

"""
LOGGING SETUP
─────────────
WHY logging instead of print()?

print()  → disappears after console closes, no timestamps, messy
logging  → timestamps, severity levels, can save to file
          professional practice that Big 4 expects

Levels:
  DEBUG    → detailed debugging info
  INFO     → general progress messages
  WARNING  → something unexpected but not broken
  ERROR    → something failed
"""

import logging
import sys


def setup_logger(name: str = "ai_report_gen") -> logging.Logger:
    """Create and configure a logger"""

    logger = logging.getLogger(name)

    # Only add handler if not already added (prevents duplicate logs)
    if not logger.handlers:
        logger.setLevel(logging.INFO)

        # Console handler — prints to terminal
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setLevel(logging.INFO)

        # Format: timestamp | level | module | message
        formatter = logging.Formatter(
            "%(asctime)s | %(levelname)-7s | %(module)s | %(message)s",
            datefmt="%H:%M:%S"
        )
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)

    return logger


# Create default logger — import this in other files
# Usage: from src.utils.logger import logger
#        logger.info("Data loaded successfully")
#        logger.error("File not found")
logger = setup_logger()