# -*- coding: utf-8 -*-
"""generate_sample_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# data/generate_sample_data.py

"""
SAMPLE DATA GENERATOR
─────────────────────
Generates realistic-looking business data for testing.

WHY not just download a Kaggle dataset?
1. You control the characteristics (trends, anomalies, seasonality)
2. You know exactly what insights SHOULD be found (for testing)
3. Shows recruiters you understand data generation
4. No licensing/attribution issues

This generates a SALES dataset with:
- 1000 transactions over 12 months
- 5 regions, 5 products, 4 categories
- Seasonality (Q4 spike — like real retail)
- Some anomalies (unusually large orders)
- Missing values (like real data)
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta


def generate_sales_data(n_records: int = 1000) -> pd.DataFrame:
    """
    Generate realistic sales transaction data.

    Parameters:
    -----------
    n_records : int
        Number of rows to generate (default 1000)

    Returns:
    --------
    pd.DataFrame with columns:
        date, region, product, category, sales_rep,
        revenue, cost, quantity, customer_id
    """

    # Set seed for reproducibility
    # WHY? So every time you run this, you get SAME data
    # Makes debugging and testing consistent
    np.random.seed(42)

    # ── Generate Dates ──────────────────────────────────
    # Spread across 2024, with more transactions in Q4
    start_date = datetime(2024, 1, 1)
    end_date = datetime(2024, 12, 31)
    total_days = (end_date - start_date).days

    # Create dates with Q4 bias (more sales in Oct-Dec)
    dates = []
    for _ in range(n_records):
        # 40% chance of Q4 date, 60% spread across Q1-Q3
        if np.random.random() < 0.4:
            # Q4: Oct-Dec (day 274 to 365)
            day_offset = np.random.randint(274, total_days + 1)
        else:
            # Q1-Q3: Jan-Sep (day 0 to 273)
            day_offset = np.random.randint(0, 274)
        dates.append(start_date + timedelta(days=day_offset))


    # ── Generate Categorical Columns ────────────────────

    # Regions with unequal distribution (realistic)
    regions = np.random.choice(
        ['North', 'South', 'East', 'West', 'Central'],
        size=n_records,
        p=[0.28, 0.22, 0.20, 0.18, 0.12]
        # North is strongest region, Central is smallest
    )

    # Products
    products = np.random.choice(
        ['Laptop Pro', 'Wireless Mouse', 'USB-C Hub',
         'Monitor 27"', 'Keyboard Mech'],
        size=n_records,
        p=[0.30, 0.25, 0.20, 0.15, 0.10]
        # Laptop Pro is best seller
    )

    # Categories
    categories = np.random.choice(
        ['Electronics', 'Accessories', 'Peripherals', 'Displays'],
        size=n_records,
        p=[0.35, 0.25, 0.25, 0.15]
    )

    # Sales Representatives
    sales_reps = np.random.choice(
        ['Alice Johnson', 'Bob Smith', 'Carol Davis',
         'David Wilson', 'Emma Brown', 'Frank Miller'],
        size=n_records
    )


    # ── Generate Numeric Columns ────────────────────────

    # Revenue: log-normal distribution (realistic for sales)
    # Most transactions are small-medium, few are very large
    base_revenue = np.random.lognormal(
        mean=5.5,    # ln(mean) ≈ $245
        sigma=0.8,   # spread
        size=n_records
    )

    # Add seasonality: Q4 revenue is 30-50% higher
    seasonal_multiplier = []
    for d in dates:
        month = d.month
        if month in [11, 12]:        # Nov-Dec: holiday season
            seasonal_multiplier.append(np.random.uniform(1.3, 1.5))
        elif month in [9, 10]:       # Sep-Oct: back to school/office
            seasonal_multiplier.append(np.random.uniform(1.1, 1.3))
        elif month in [1, 2]:        # Jan-Feb: post-holiday dip
            seasonal_multiplier.append(np.random.uniform(0.7, 0.9))
        else:                         # Normal months
            seasonal_multiplier.append(np.random.uniform(0.95, 1.1))

    revenue = base_revenue * np.array(seasonal_multiplier)
    revenue = np.round(revenue, 2)

    # Quantity: 1-25 units per transaction
    quantity = np.random.randint(1, 26, size=n_records)

    # Cost: 40-70% of revenue (realistic margins)
    cost_ratio = np.random.uniform(0.40, 0.70, size=n_records)
    cost = np.round(revenue * cost_ratio, 2)

    # Customer IDs
    # ~300 unique customers (some are repeat buyers)
    customer_ids = [f'CUST-{np.random.randint(1000, 1300)}' for _ in range(n_records)]


    # ── Inject Anomalies ────────────────────────────────
    # Real data has outliers — our anomaly detector should find these

    # 10 unusually LARGE transactions (enterprise deals)
    large_anomaly_idx = np.random.choice(n_records, 10, replace=False)
    revenue[large_anomaly_idx] *= np.random.uniform(5, 12, size=10)
    quantity[large_anomaly_idx] = np.random.randint(50, 200, size=10)
    cost[large_anomaly_idx] = revenue[large_anomaly_idx] * 0.5  # better margins on big deals

    # 5 unusually SMALL transactions (maybe errors or samples)
    small_anomaly_idx = np.random.choice(
        [i for i in range(n_records) if i not in large_anomaly_idx],
        5, replace=False
    )
    revenue[small_anomaly_idx] = np.random.uniform(0.5, 2.0, size=5)
    quantity[small_anomaly_idx] = 1


    # ── Build DataFrame ─────────────────────────────────
    df = pd.DataFrame({
        'date': dates,
        'region': regions,
        'product': products,
        'category': categories,
        'sales_rep': sales_reps,
        'revenue': np.round(revenue, 2),
        'cost': np.round(cost, 2),
        'quantity': quantity.astype(int),
        'customer_id': customer_ids,
    })


    # ── Inject Missing Values ───────────────────────────
    # Real data is NEVER perfectly clean
    # Randomly set ~2% of some columns to NaN

    for col in ['revenue', 'cost', 'region']:
        mask = np.random.random(n_records) < 0.02    # 2% chance
        df.loc[mask, col] = np.nan


    # ── Sort by Date & Reset Index ──────────────────────
    df = df.sort_values('date').reset_index(drop=True)


    # ── Add Derived Column ──────────────────────────────
    df['profit'] = np.round(df['revenue'] - df['cost'], 2)


    # ── Save to CSV ─────────────────────────────────────
    output_path = 'data/sample_sales.csv'
    df.to_csv(output_path, index=False)
    print(f"✅ Generated {len(df)} records → {output_path}")
    print(f"   Date range: {df['date'].min()} to {df['date'].max()}")
    print(f"   Columns: {list(df.columns)}")
    print(f"   Missing values: {df.isnull().sum().sum()} total")
    print(f"   Revenue range: ${df['revenue'].min():.2f} to ${df['revenue'].max():.2f}")

    return df


# ── Run directly ────────────────────────────────────────
if __name__ == "__main__":
    df = generate_sales_data(1000)
    print("\n📊 First 5 rows:")
    print(df.head().to_string())
    print(f"\n📊 Shape: {df.shape}")
    print(f"\n📊 Dtypes:\n{df.dtypes}")