# -*- coding: utf-8 -*-
"""anomaly_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/analysis/anomaly_detector.py

"""
ANOMALY DETECTION MODULE
─────────────────────────
Detects outliers, unusual patterns, and data quality issues.

METHODS USED:
1. IQR Method (Interquartile Range) — robust to distribution shape
2. Z-Score Method — assumes normal distribution
3. Business Rule Checks — domain-specific anomalies
4. Time-Based Anomalies — sudden spikes/drops in trends

WHY MULTIPLE METHODS?
No single method catches everything:
- IQR is great for skewed data (like revenue)
- Z-score is great for normal data (like test scores)
- Business rules catch domain-specific issues
  (e.g., negative salary, 200% growth in one day)

Together they provide comprehensive anomaly coverage.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional
from scipy import stats
from src.utils.logger import logger


class AnomalyDetector:
    """
    Detects anomalies using multiple statistical methods.

    Usage:
        detector = AnomalyDetector()
        results = detector.detect(df)
    """

    def detect(self, df: pd.DataFrame,
               sensitivity: str = "medium") -> Dict:
        """
        Run all anomaly detection methods.

        Parameters:
        -----------
        df : pd.DataFrame
            The dataset to analyze
        sensitivity : str
            'low' = only flag extreme outliers
            'medium' = balanced (recommended)
            'high' = flag more potential issues

        Returns:
        --------
        Dict with anomalies by column, summaries, and alerts
        """

        logger.info(f"Starting anomaly detection (sensitivity: {sensitivity})")

        # Set thresholds based on sensitivity
        thresholds = self._get_thresholds(sensitivity)

        numeric_cols = df.select_dtypes(include=[np.number]).columns

        results = {
            "column_anomalies": {},
            "time_anomalies": {},
            "business_rule_alerts": [],
            "summary": {},
            "sensitivity": sensitivity,
        }

        # ── 1. Column-level anomalies ───────────────────
        for col in numeric_cols:
            col_anomalies = self._detect_column_anomalies(
                df[col], col, thresholds
            )
            if col_anomalies["total_anomalies"] > 0:
                results["column_anomalies"][col] = col_anomalies

        # ── 2. Time-based anomalies ─────────────────────
        date_col = self._find_date_column(df)
        if date_col:
            for col in numeric_cols:
                time_anomalies = self._detect_time_anomalies(
                    df, date_col, col, thresholds
                )
                if time_anomalies and time_anomalies.get("spikes"):
                    results["time_anomalies"][col] = time_anomalies

        # ── 3. Business rule checks ─────────────────────
        results["business_rule_alerts"] = self._business_rule_checks(df)

        # ── 4. Generate summary ─────────────────────────
        results["summary"] = self._generate_summary(results)
        results["alerts"] = self._generate_alerts(results)

        logger.info(
            f"Anomaly detection complete: "
            f"{results['summary']['total_anomalies']} anomalies found"
        )

        return results


    def _get_thresholds(self, sensitivity: str) -> Dict:
        """
        Return detection thresholds based on sensitivity level.

        LOW sensitivity  → only catches EXTREME outliers (fewer false positives)
        HIGH sensitivity → catches more anomalies (more false positives)
        """

        thresholds = {
            "low": {
                "iqr_multiplier": 3.0,     # very strict
                "zscore_threshold": 3.5,
                "pct_change_spike": 200,   # 200% change
            },
            "medium": {
                "iqr_multiplier": 1.5,     # standard
                "zscore_threshold": 3.0,
                "pct_change_spike": 100,   # 100% change
            },
            "high": {
                "iqr_multiplier": 1.0,     # catches more
                "zscore_threshold": 2.5,
                "pct_change_spike": 50,    # 50% change
            },
        }

        return thresholds.get(sensitivity, thresholds["medium"])


    def _detect_column_anomalies(self, series: pd.Series,
                                  col_name: str,
                                  thresholds: Dict) -> Dict:
        """
        Detect outliers in a single numeric column using IQR + Z-score.

        IQR Method:
        ───────────
        Q1 = 25th percentile
        Q3 = 75th percentile
        IQR = Q3 - Q1
        Lower bound = Q1 - 1.5 × IQR
        Upper bound = Q3 + 1.5 × IQR
        Anything outside these bounds = outlier

        Z-Score Method:
        ───────────────
        Z = (value - mean) / std_dev
        |Z| > 3 means the value is 3 standard deviations from mean
        Only ~0.3% of data should be this extreme
        """

        clean = series.dropna()

        if len(clean) < 10:
            return {"total_anomalies": 0, "reason": "Too few values"}

        # ── IQR Method ──────────────────────────────────
        Q1 = clean.quantile(0.25)
        Q3 = clean.quantile(0.75)
        IQR = Q3 - Q1

        multiplier = thresholds["iqr_multiplier"]
        lower_bound = Q1 - multiplier * IQR
        upper_bound = Q3 + multiplier * IQR

        iqr_outlier_mask = (clean < lower_bound) | (clean > upper_bound)
        iqr_outliers = clean[iqr_outlier_mask]

        # Classify as upper or lower outliers
        upper_outliers = clean[clean > upper_bound]
        lower_outliers = clean[clean < lower_bound]

        # ── Z-Score Method ──────────────────────────────
        z_threshold = thresholds["zscore_threshold"]
        z_scores = np.abs(stats.zscore(clean, nan_policy='omit'))
        zscore_outlier_mask = z_scores > z_threshold
        zscore_outliers = clean[zscore_outlier_mask]

        # ── Combine Results ─────────────────────────────
        all_outlier_indices = set(iqr_outliers.index) | set(zscore_outliers.index)
        total_anomalies = len(all_outlier_indices)

        result = {
            "total_anomalies": total_anomalies,
            "anomaly_percentage": round(total_anomalies / len(clean) * 100, 2),
            "iqr_method": {
                "Q1": round(float(Q1), 2),
                "Q3": round(float(Q3), 2),
                "IQR": round(float(IQR), 2),
                "lower_bound": round(float(lower_bound), 2),
                "upper_bound": round(float(upper_bound), 2),
                "outliers_count": len(iqr_outliers),
                "upper_outliers_count": len(upper_outliers),
                "lower_outliers_count": len(lower_outliers),
            },
            "zscore_method": {
                "threshold": z_threshold,
                "outliers_count": len(zscore_outliers),
                "max_zscore": round(float(z_scores.max()), 2),
            },
            "outlier_values": {
                "highest": sorted(
                    upper_outliers.head(5).tolist(), reverse=True
                ) if len(upper_outliers) > 0 else [],
                "lowest": sorted(
                    lower_outliers.head(5).tolist()
                ) if len(lower_outliers) > 0 else [],
            },
            "severity": self._classify_severity(total_anomalies, len(clean)),
            "interpretation": self._interpret_column_anomalies(
                col_name, total_anomalies, len(clean),
                len(upper_outliers), len(lower_outliers),
                lower_bound, upper_bound
            ),
        }

        return result


    def _detect_time_anomalies(self, df: pd.DataFrame,
                                date_col: str, value_col: str,
                                thresholds: Dict) -> Optional[Dict]:
        """
        Detect sudden spikes or drops in time series data.

        Looks for periods where the value changed by more than
        the threshold percentage compared to the previous period.

        EXAMPLE:
        Revenue was $100K → $250K → spike of +150% → ANOMALY

        WHY TIME ANOMALIES SEPARATELY?
        A value might not be an outlier overall, but could be
        a sudden spike compared to the PREVIOUS period.
        """

        try:
            temp_df = df[[date_col, value_col]].copy()
            temp_df[date_col] = pd.to_datetime(temp_df[date_col], errors='coerce')
            temp_df = temp_df.dropna()

            # Resample to monthly
            temp_df = temp_df.set_index(date_col)
            monthly = temp_df[value_col].resample('M').sum()

            if len(monthly) < 3:
                return None

            # Calculate period-over-period changes
            pct_change = monthly.pct_change().dropna()
            pct_change = pct_change.replace([np.inf, -np.inf], np.nan).dropna()

            spike_threshold = thresholds["pct_change_spike"] / 100
            spikes = pct_change[abs(pct_change) > spike_threshold]

            if len(spikes) == 0:
                return None

            spike_details = []
            for date, change in spikes.items():
                spike_details.append({
                    "date": str(date.strftime('%Y-%m-%d')),
                    "change_pct": round(float(change * 100), 1),
                    "direction": "spike ⬆️" if change > 0 else "drop ⬇️",
                    "value": round(float(monthly.loc[date]), 2),
                    "severity": "critical" if abs(change) > 2 else "warning",
                })

            return {
                "spikes": spike_details,
                "total_spikes": len(spikes),
            }

        except Exception as e:
            logger.warning(f"Error in time anomaly detection for {value_col}: {e}")
            return None


    def _business_rule_checks(self, df: pd.DataFrame) -> List[Dict]:
        """
        Check for domain-independent business rule violations.

        These are things that are ALWAYS wrong regardless of domain:
        - Negative values where they shouldn't exist
        - Zero values that seem suspicious
        - Future dates
        - Extreme ratios between related columns
        """

        alerts = []

        numeric_cols = df.select_dtypes(include=[np.number]).columns

        for col in numeric_cols:
            col_lower = col.lower()

            # Rule 1: Negative values in typically-positive columns
            positive_indicators = [
                'revenue', 'sales', 'price', 'cost', 'quantity',
                'salary', 'age', 'units', 'amount', 'count'
            ]

            if any(indicator in col_lower for indicator in positive_indicators):
                negative_count = (df[col] < 0).sum()
                if negative_count > 0:
                    alerts.append({
                        "type": "negative_values",
                        "severity": "high",
                        "emoji": "🔴",
                        "column": col,
                        "count": int(negative_count),
                        "message": (
                            f"**{col}** has {negative_count} negative values. "
                            f"This column typically should be positive. "
                            f"Minimum value: {df[col].min():,.2f}"
                        ),
                    })

            # Rule 2: Zero values in key metric columns
            zero_indicators = ['revenue', 'sales', 'salary', 'price']
            if any(indicator in col_lower for indicator in zero_indicators):
                zero_count = (df[col] == 0).sum()
                if zero_count > 0:
                    zero_pct = zero_count / len(df) * 100
                    if zero_pct > 5:      # more than 5% zeros is suspicious
                        alerts.append({
                            "type": "suspicious_zeros",
                            "severity": "medium",
                            "emoji": "🟡",
                            "column": col,
                            "count": int(zero_count),
                            "message": (
                                f"**{col}** has {zero_count} zero values "
                                f"({zero_pct:.1f}%). This may indicate "
                                f"missing data or processing errors."
                            ),
                        })

        # Rule 3: Future dates
        date_cols = df.select_dtypes(include=['datetime64']).columns
        for col in date_cols:
            future_count = (df[col] > pd.Timestamp.now()).sum()
            if future_count > 0:
                alerts.append({
                    "type": "future_dates",
                    "severity": "medium",
                    "emoji": "🟡",
                    "column": col,
                    "count": int(future_count),
                    "message": (
                        f"**{col}** has {future_count} dates in the future. "
                        f"This may indicate data entry errors."
                    ),
                })

        # Rule 4: High null percentage
        for col in df.columns:
            null_pct = df[col].isnull().mean() * 100
            if null_pct > 20:
                alerts.append({
                    "type": "high_nulls",
                    "severity": "medium" if null_pct < 50 else "high",
                    "emoji": "🟡" if null_pct < 50 else "🔴",
                    "column": col,
                    "count": int(df[col].isnull().sum()),
                    "message": (
                        f"**{col}** has {null_pct:.1f}% missing values. "
                        f"Consider investigating the data source."
                    ),
                })

        return alerts


    def _classify_severity(self, n_anomalies: int, n_total: int) -> str:
        """Classify anomaly severity based on percentage"""
        pct = (n_anomalies / n_total) * 100 if n_total > 0 else 0

        if pct > 10:
            return "critical"
        elif pct > 5:
            return "high"
        elif pct > 2:
            return "medium"
        else:
            return "low"


    def _interpret_column_anomalies(self, col_name, total, n_total,
                                     upper, lower,
                                     lb, ub) -> str:
        """Generate human-readable interpretation"""

        pct = round(total / n_total * 100, 1) if n_total > 0 else 0

        parts = [f"Found **{total} anomalies** ({pct}%) in '{col_name}'."]

        if upper > 0:
            parts.append(
                f"**{upper}** unusually HIGH values (above {ub:,.2f})."
            )
        if lower > 0:
            parts.append(
                f"**{lower}** unusually LOW values (below {lb:,.2f})."
            )

        if pct > 5:
            parts.append("⚠️ This is a significant anomaly rate — investigate the data source.")
        elif pct > 2:
            parts.append("Some outliers present — may be valid extreme cases or data issues.")
        else:
            parts.append("Anomaly rate is within normal range.")

        return " ".join(parts)


    def _generate_summary(self, results: Dict) -> Dict:
        """Generate overall anomaly summary"""

        total_col_anomalies = sum(
            data["total_anomalies"]
            for data in results["column_anomalies"].values()
        )

        total_time_anomalies = sum(
            data.get("total_spikes", 0)
            for data in results["time_anomalies"].values()
        )

        total_alerts = len(results["business_rule_alerts"])

        total = total_col_anomalies + total_time_anomalies + total_alerts

        # Overall severity
        severities = [
            data["severity"]
            for data in results["column_anomalies"].values()
        ]
        severities += [
            alert["severity"]
            for alert in results["business_rule_alerts"]
        ]

        if "critical" in severities:
            overall_severity = "critical"
        elif "high" in severities:
            overall_severity = "high"
        elif "medium" in severities:
            overall_severity = "medium"
        else:
            overall_severity = "low"

        severity_emoji = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢"
        }

        return {
            "total_anomalies": total,
            "column_anomalies_count": total_col_anomalies,
            "time_anomalies_count": total_time_anomalies,
            "business_alerts_count": total_alerts,
            "affected_columns": list(results["column_anomalies"].keys()),
            "overall_severity": overall_severity,
            "severity_emoji": severity_emoji.get(overall_severity, "🟢"),
        }


    def _generate_alerts(self, results: Dict) -> List[Dict]:
        """
        Generate a flat list of all alerts sorted by severity.
        This is what gets displayed in the Streamlit UI.
        """

        alerts = []
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}

        # Column anomalies as alerts
        for col, data in results["column_anomalies"].items():
            alerts.append({
                "type": "statistical_outlier",
                "severity": data["severity"],
                "emoji": "📊",
                "title": f"Outliers in {col}",
                "message": data["interpretation"],
            })

        # Time anomalies as alerts
        for col, data in results["time_anomalies"].items():
            for spike in data.get("spikes", []):
                alerts.append({
                    "type": "time_spike",
                    "severity": spike["severity"],
                    "emoji": "⚡",
                    "title": f"Sudden {spike['direction']} in {col}",
                    "message": (
                        f"{spike['direction']} of **{spike['change_pct']}%** "
                        f"detected on {spike['date']} "
                        f"(value: {spike['value']:,.2f})"
                    ),
                })

        # Business rule alerts
        for alert in results["business_rule_alerts"]:
            alerts.append({
                "type": alert["type"],
                "severity": alert["severity"],
                "emoji": alert["emoji"],
                "title": f"{alert['type'].replace('_', ' ').title()} in {alert['column']}",
                "message": alert["message"],
            })

        # Sort by severity
        alerts.sort(key=lambda x: severity_order.get(x["severity"], 99))

        return alerts


    def _find_date_column(self, df: pd.DataFrame) -> Optional[str]:
        """Find datetime column"""
        datetime_cols = df.select_dtypes(include=['datetime64']).columns
        return datetime_cols[0] if len(datetime_cols) > 0 else None