# -*- coding: utf-8 -*-
"""domain_config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/analysis/domain_config.py

"""
DOMAIN CONFIGURATION REGISTRY
──────────────────────────────────────────────────────
Now includes AnalysisConfig, ChartConfig, and DomainVocabulary
for EVERY domain.

This is the SINGLE SOURCE OF TRUTH that controls:
  1. How columns are detected
  2. What KPIs are calculated
  3. How data is analyzed (COUNT vs SUM vs MEAN)
  4. What charts are generated
  5. What language the AI uses in reports

ADDING A NEW DOMAIN:
  1. Create column patterns
  2. Create KPI definitions
  3. Create AnalysisConfig (what questions to answer)
  4. Create ChartConfig (what charts to show)
  5. Create DomainVocabulary (what language to use)
  6. Bundle into DomainConfig
  7. Add to DOMAIN_REGISTRY
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# ═══════════════════════════════════════════════════════════
# DATA CLASSES — Building Blocks
# ═══════════════════════════════════════════════════════════

@dataclass
class ColumnPatterns:
    """Maps metric roles → possible column name patterns"""
    patterns: Dict[str, List[str]] = field(default_factory=dict)


@dataclass
class KPIDefinition:
    """Defines a single KPI"""
    name: str
    key: str
    description: str
    format: str = "{:,.2f}"
    icon: str = "📊"
    requires: List[str] = field(default_factory=list)


@dataclass
class CrossTabDefinition:
    """
    Defines a cross-tabulation analysis.

    Example for Healthcare:
        row = "gender"
        col = "diagnosis"
        value = "patient_id"
        aggregation = "count"
        title = "Patient Count by Gender and Diagnosis"

    This produces a table like:
                    Diabetes  Hypertension  Fracture
        Male           45          62          28
        Female         52          58          31
    """
    row: str                    # column pattern role for rows
    col: str                    # column pattern role for columns
    value: str                  # column pattern role for values
    aggregation: str            # "count", "sum", "mean"
    title: str                  # display title
    description: str = ""       # what insight this reveals


@dataclass
class GroupByAnalysis:
    """
    Defines a group-by analysis.

    Instead of always doing SUM(revenue) GROUP BY category,
    this tells the system EXACTLY how to aggregate.

    Example for Healthcare:
        group_by_role = "diagnosis"
        metric_role = "patient"
        aggregation = "count"
        title = "Patient Count by Diagnosis"
        sort_by = "count"
        show_percentage = True

    Example for HR:
        group_by_role = "department"
        metric_role = "compensation"
        aggregation = "mean"
        title = "Average Salary by Department"
        sort_by = "mean"
        show_percentage = False
    """
    group_by_role: str          # column pattern role to group by
    metric_role: str            # column pattern role to aggregate
    aggregation: str            # "count", "sum", "mean", "median"
    title: str                  # display title
    sort_by: str = "desc"       # "desc" or "asc"
    show_percentage: bool = True
    description: str = ""


@dataclass
class DomainChartSpec:
    """
    Defines a specific chart for this domain.

    Instead of auto-guessing chart types, each domain
    EXPLICITLY defines what charts are meaningful.
    """
    chart_type: str             # "bar", "pie", "histogram", "box", "grouped_bar", "scatter"
    title: str
    x_role: str                 # column pattern role for x-axis
    y_role: Optional[str]       # column pattern role for y-axis (None for count-based)
    color_role: Optional[str] = None    # column pattern role for color grouping
    aggregation: str = "sum"    # "count", "sum", "mean", "median", "raw"
    priority: int = 5           # 1=most important
    reason: str = ""            # why this chart matters
    section: str = "general"    # report section
    max_categories: int = 15    # limit categories shown


@dataclass
class DomainVocabulary:
    """
    Domain-specific language for reports.

    Controls how the AI narrator speaks about the data.
    Prevents calling patients "customers" or
    calling salary "revenue".
    """
    entity_name: str            # "patients", "employees", "transactions"
    entity_plural: str          # "patients", "employees", "orders"
    primary_metric_name: str    # "patient count", "headcount", "revenue"
    primary_metric_verb: str    # "admitted", "employed", "generated"

    # Words to USE in this domain
    preferred_terms: List[str] = field(default_factory=list)

    # Words to NEVER USE in this domain
    forbidden_terms: List[str] = field(default_factory=list)

    # How to describe good performance
    positive_descriptors: List[str] = field(default_factory=list)

    # How to describe bad performance
    negative_descriptors: List[str] = field(default_factory=list)

    # Domain-specific insight prompts
    insight_questions: List[str] = field(default_factory=list)


@dataclass
class AnalysisConfig:
    """
    MASTER ANALYSIS CONFIGURATION for a domain.

    This is the "recipe" that tells descriptive.py:
    - What is the primary thing to count/sum/average?
    - What columns to group by?
    - What cross-tabs to compute?
    - What distributions to analyze?
    - What comparisons make sense?
    """

    # Primary metric: what is THE main thing we're measuring?
    primary_metric_role: str            # e.g., "revenue", "patient", "employee_id"
    primary_aggregation: str            # "sum", "count", "mean"

    # Secondary metrics
    secondary_metrics: List[Dict] = field(default_factory=list)
    # Each dict: {"role": "cost", "aggregation": "sum", "label": "Total Cost"}

    # Group-by analyses to perform
    group_by_analyses: List[GroupByAnalysis] = field(default_factory=list)

    # Cross-tabulations
    cross_tabs: List[CrossTabDefinition] = field(default_factory=list)

    # Distribution analyses (which numeric columns to show histograms for)
    distribution_roles: List[str] = field(default_factory=list)

    # Correlation pairs to check (which role pairs to correlate)
    correlation_pairs: List[Tuple[str, str]] = field(default_factory=list)

    # Columns to NEVER group by (high cardinality identifiers)
    exclude_from_groupby: List[str] = field(default_factory=list)

    # How to define "top/bottom performers" in this domain
    performer_metric_role: str = ""         # what metric defines performance
    performer_aggregation: str = "sum"      # how to aggregate for ranking
    performer_label: str = "Top Performers" # display label


@dataclass
class DomainConfig:
    """Complete configuration for a business domain"""
    domain_id: str
    display_name: str
    description: str
    icon: str
    column_patterns: ColumnPatterns
    kpi_definitions: List[KPIDefinition]
    analysis_config: AnalysisConfig
    chart_specs: List[DomainChartSpec]
    vocabulary: DomainVocabulary
    llm_context: str
    category_columns_hints: List[str]


# ═══════════════════════════════════════════════════════════
# DOMAIN 1: SALES & REVENUE
# ═══════════════════════════════════════════════════════════

SALES_DOMAIN = DomainConfig(
    domain_id="sales",
    display_name="Sales & Revenue",
    description="Sales transactions, revenue data, order data",
    icon="💰",

    column_patterns=ColumnPatterns(patterns={
        "revenue": [
            'revenue', 'sales', 'amount', 'total_sales',
            'order_amount', 'transaction_amount', 'gmv',
            'turnover', 'income', 'order_value'
        ],
        "cost": [
            'cost', 'cogs', 'expense', 'cost_price',
            'unit_cost', 'total_cost', 'purchase_price'
        ],
        "quantity": [
            'quantity', 'qty', 'units', 'units_sold',
            'order_quantity', 'items', 'pieces', 'volume'
        ],
        "profit": [
            'profit', 'margin', 'gross_profit', 'net_profit',
            'earnings', 'net_income'
        ],
        "customer": [
            'customer', 'customer_id', 'client', 'buyer',
            'account', 'cust_id', 'client_id'
        ],
        "product": [
            'product', 'item', 'sku', 'product_name',
            'item_name', 'merchandise'
        ],
        "region": [
            'region', 'territory', 'area', 'zone',
            'location', 'city', 'state', 'country', 'market'
        ],
        "category": [
            'category', 'product_category', 'segment',
            'type', 'class', 'group'
        ],
        "channel": [
            'channel', 'source', 'platform', 'medium'
        ],
        "date": [
            'date', 'order_date', 'transaction_date',
            'sale_date', 'invoice_date', 'created_at'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Revenue", "total_revenue", "Sum of all revenue", "${:,.0f}", "💰", ["revenue"]),
        KPIDefinition("Total Cost", "total_cost", "Sum of all costs", "${:,.0f}", "💸", ["cost"]),
        KPIDefinition("Gross Profit", "gross_profit", "Revenue minus Cost", "${:,.0f}", "📈", ["revenue", "cost"]),
        KPIDefinition("Profit Margin", "profit_margin_pct", "Profit as % of Revenue", "{:.1f}%", "📊", ["revenue", "cost"]),
        KPIDefinition("Total Units Sold", "total_units", "Total quantity sold", "{:,.0f}", "📦", ["quantity"]),
        KPIDefinition("Avg Order Value", "avg_order_value", "Average revenue per transaction", "${:,.2f}", "💵", ["revenue"]),
        KPIDefinition("Avg Price/Unit", "avg_price_per_unit", "Revenue divided by units", "${:,.2f}", "🏷️", ["revenue", "quantity"]),
        KPIDefinition("Total Transactions", "total_transactions", "Number of records", "{:,.0f}", "🔢", []),
        KPIDefinition("Unique Customers", "unique_customers", "Distinct customer count", "{:,.0f}", "👥", ["customer"]),
        KPIDefinition("Revenue/Customer", "revenue_per_customer", "Avg revenue per customer", "${:,.2f}", "💳", ["revenue", "customer"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="revenue",
        primary_aggregation="sum",

        secondary_metrics=[
            {"role": "cost", "aggregation": "sum", "label": "Total Cost"},
            {"role": "profit", "aggregation": "sum", "label": "Total Profit"},
            {"role": "quantity", "aggregation": "sum", "label": "Total Units"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="region",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Region",
                description="Which regions generate the most revenue?"
            ),
            GroupByAnalysis(
                group_by_role="product",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Product",
                description="Which products are top sellers?"
            ),
            GroupByAnalysis(
                group_by_role="category",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Category",
                description="Revenue distribution across categories"
            ),
            GroupByAnalysis(
                group_by_role="region",
                metric_role="revenue",
                aggregation="mean",
                title="Average Order Value by Region",
                description="Which regions have highest average transactions?"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="region",
                col="product",
                value="revenue",
                aggregation="sum",
                title="Revenue: Region × Product",
                description="How does product performance vary by region?"
            ),
            CrossTabDefinition(
                row="region",
                col="category",
                value="revenue",
                aggregation="sum",
                title="Revenue: Region × Category",
                description="Category performance across regions"
            ),
        ],

        distribution_roles=["revenue", "quantity", "profit"],

        correlation_pairs=[
            ("revenue", "cost"),
            ("revenue", "quantity"),
            ("quantity", "profit"),
        ],

        exclude_from_groupby=["customer", "date"],

        performer_metric_role="revenue",
        performer_aggregation="sum",
        performer_label="Revenue Leaders",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="line",
            title="Revenue Trend Over Time",
            x_role="date", y_role="revenue",
            aggregation="sum", priority=1,
            reason="Track revenue trajectory over time",
            section="trends"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Revenue by Region",
            x_role="region", y_role="revenue",
            aggregation="sum", priority=2,
            reason="Compare regional performance",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Revenue by Product",
            x_role="product", y_role="revenue",
            aggregation="sum", priority=3,
            reason="Identify top-selling products",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Revenue Share by Category",
            x_role="category", y_role="revenue",
            aggregation="sum", priority=4,
            reason="Proportional category contribution",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Order Value Distribution",
            x_role="revenue", y_role=None,
            aggregation="raw", priority=5,
            reason="Understand transaction size patterns",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Revenue vs Cost",
            x_role="revenue", y_role="cost",
            aggregation="raw", priority=6,
            reason="Explore revenue-cost relationship",
            section="relationships"
        ),
        DomainChartSpec(
            chart_type="grouped_bar",
            title="Revenue by Region & Category",
            x_role="region", y_role="revenue",
            color_role="category",
            aggregation="sum", priority=7,
            reason="Multi-dimensional performance view",
            section="comparison"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="transaction",
        entity_plural="transactions",
        primary_metric_name="revenue",
        primary_metric_verb="generated",
        preferred_terms=[
            "revenue", "sales", "orders", "customers",
            "profit margin", "average order value", "conversion",
            "growth", "market share", "channel performance"
        ],
        forbidden_terms=[
            "patients", "employees", "headcount", "diagnosis",
            "attrition", "clinical", "treatment"
        ],
        positive_descriptors=[
            "strong revenue growth", "healthy margins",
            "robust sales performance", "impressive order volume"
        ],
        negative_descriptors=[
            "declining revenue", "margin compression",
            "falling sales", "customer churn"
        ],
        insight_questions=[
            "Which region drives the most revenue?",
            "What is the profit margin trend?",
            "Which products are underperforming?",
            "Is average order value increasing or decreasing?",
            "Are there seasonal sales patterns?",
        ],
    ),

    llm_context=(
        "This is a sales/revenue dataset. Focus on revenue trends, "
        "profitability analysis, top-performing products and regions, "
        "customer value, and sales growth patterns. "
        "Use financial/business terminology."
    ),

    category_columns_hints=["region", "product", "category", "channel", "segment"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 2: HR & WORKFORCE
# ═══════════════════════════════════════════════════════════

HR_DOMAIN = DomainConfig(
    domain_id="hr",
    display_name="HR & Workforce",
    description="Employee data, workforce analytics, HR metrics",
    icon="👥",

    column_patterns=ColumnPatterns(patterns={
        "compensation": [
            'salary', 'pay', 'wage', 'compensation', 'ctc',
            'annual_salary', 'monthly_salary', 'base_pay',
            'total_compensation', 'income', 'earnings'
        ],
        "department": [
            'department', 'dept', 'division', 'team',
            'business_unit', 'function', 'group'
        ],
        "job_title": [
            'title', 'job_title', 'position', 'role',
            'designation', 'job_role', 'job_name'
        ],
        "employee_id": [
            'employee', 'emp_id', 'employee_id', 'staff_id',
            'worker_id', 'personnel', 'emp_no', 'id'
        ],
        "tenure": [
            'tenure', 'years', 'experience', 'service_years',
            'years_at_company', 'months_employed', 'duration'
        ],
        "performance": [
            'performance', 'rating', 'score', 'review',
            'evaluation', 'appraisal', 'kpi_score'
        ],
        "attrition": [
            'attrition', 'left', 'terminated', 'resigned',
            'churned', 'active', 'status', 'employment_status'
        ],
        "age": [
            'age', 'birth_year', 'dob', 'date_of_birth'
        ],
        "gender": [
            'gender', 'sex'
        ],
        "education": [
            'education', 'degree', 'qualification',
            'education_level', 'academic'
        ],
        "location": [
            'location', 'office', 'city', 'branch',
            'site', 'region', 'country'
        ],
        "date": [
            'hire_date', 'joining_date', 'start_date',
            'date_of_joining', 'onboard_date', 'date'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Headcount", "total_headcount", "Total number of employees", "{:,.0f}", "👥", []),
        KPIDefinition("Avg Salary", "avg_salary", "Average compensation", "${:,.0f}", "💰", ["compensation"]),
        KPIDefinition("Median Salary", "median_salary", "Median compensation", "${:,.0f}", "💵", ["compensation"]),
        KPIDefinition("Total Payroll", "total_payroll", "Sum of all compensation", "${:,.0f}", "💸", ["compensation"]),
        KPIDefinition("Salary Range", "salary_range", "Max minus Min salary", "${:,.0f}", "📊", ["compensation"]),
        KPIDefinition("Departments", "total_departments", "Number of departments", "{:,.0f}", "🏢", ["department"]),
        KPIDefinition("Avg Tenure", "avg_tenure", "Average years at company", "{:.1f} yrs", "📅", ["tenure"]),
        KPIDefinition("Avg Performance", "avg_performance", "Average performance score", "{:.2f}", "⭐", ["performance"]),
        KPIDefinition("Attrition Rate", "attrition_rate", "% of employees who left", "{:.1f}%", "🚪", ["attrition"]),
        KPIDefinition("Avg Age", "avg_age", "Average employee age", "{:.0f}", "🎂", ["age"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="employee_id",
        primary_aggregation="count",

        secondary_metrics=[
            {"role": "compensation", "aggregation": "mean", "label": "Avg Salary"},
            {"role": "compensation", "aggregation": "median", "label": "Median Salary"},
            {"role": "tenure", "aggregation": "mean", "label": "Avg Tenure"},
            {"role": "performance", "aggregation": "mean", "label": "Avg Performance"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="department",
                metric_role="employee_id",
                aggregation="count",
                title="Headcount by Department",
                description="How many employees in each department?"
            ),
            GroupByAnalysis(
                group_by_role="department",
                metric_role="compensation",
                aggregation="mean",
                title="Average Salary by Department",
                show_percentage=False,
                description="Which departments have highest/lowest pay?"
            ),
            GroupByAnalysis(
                group_by_role="job_title",
                metric_role="compensation",
                aggregation="mean",
                title="Average Salary by Job Title",
                show_percentage=False,
                description="Compensation across different roles"
            ),
            GroupByAnalysis(
                group_by_role="gender",
                metric_role="employee_id",
                aggregation="count",
                title="Headcount by Gender",
                description="Gender distribution in workforce"
            ),
            GroupByAnalysis(
                group_by_role="gender",
                metric_role="compensation",
                aggregation="mean",
                title="Average Salary by Gender",
                show_percentage=False,
                description="Gender pay gap analysis"
            ),
            GroupByAnalysis(
                group_by_role="education",
                metric_role="compensation",
                aggregation="mean",
                title="Average Salary by Education Level",
                show_percentage=False,
                description="Impact of education on compensation"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="department",
                col="attrition",
                value="employee_id",
                aggregation="count",
                title="Attrition by Department",
                description="Which departments have highest attrition?"
            ),
            CrossTabDefinition(
                row="gender",
                col="department",
                value="employee_id",
                aggregation="count",
                title="Gender Distribution Across Departments",
                description="Gender balance in each department"
            ),
            CrossTabDefinition(
                row="department",
                col="performance",
                value="employee_id",
                aggregation="count",
                title="Performance Distribution by Department",
                description="How does performance vary across departments?"
            ),
            CrossTabDefinition(
                row="gender",
                col="job_title",
                value="compensation",
                aggregation="mean",
                title="Salary by Gender & Role",
                description="Pay equity analysis across roles"
            ),
        ],

        distribution_roles=["compensation", "age", "tenure", "performance"],

        correlation_pairs=[
            ("compensation", "tenure"),
            ("compensation", "performance"),
            ("age", "compensation"),
            ("tenure", "performance"),
        ],

        exclude_from_groupby=["employee_id", "date"],

        performer_metric_role="employee_id",
        performer_aggregation="count",
        performer_label="Largest Departments",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="bar",
            title="Headcount by Department",
            x_role="department", y_role="employee_id",
            aggregation="count", priority=1,
            reason="Show workforce distribution across departments",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Salary Distribution",
            x_role="compensation", y_role=None,
            aggregation="raw", priority=2,
            reason="Understand compensation spread and pay bands",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="box",
            title="Salary by Department",
            x_role="department", y_role="compensation",
            aggregation="raw", priority=3,
            reason="Compare compensation ranges across departments",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Gender Distribution",
            x_role="gender", y_role="employee_id",
            aggregation="count", priority=4,
            reason="Show workforce gender balance",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="grouped_bar",
            title="Attrition by Department",
            x_role="department", y_role="employee_id",
            color_role="attrition",
            aggregation="count", priority=5,
            reason="Identify departments with highest attrition",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Tenure Distribution",
            x_role="tenure", y_role=None,
            aggregation="raw", priority=6,
            reason="Understand employee retention patterns",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Salary vs Tenure",
            x_role="tenure", y_role="compensation",
            color_role="department",
            aggregation="raw", priority=7,
            reason="Does longer tenure correlate with higher pay?",
            section="relationships"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Average Salary by Gender",
            x_role="gender", y_role="compensation",
            aggregation="mean", priority=8,
            reason="Gender pay gap analysis",
            section="comparison"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="employee",
        entity_plural="employees",
        primary_metric_name="headcount",
        primary_metric_verb="employed",
        preferred_terms=[
            "headcount", "workforce", "employees", "compensation",
            "attrition", "retention", "tenure", "performance",
            "department", "talent", "human capital", "payroll"
        ],
        forbidden_terms=[
            "revenue", "sales", "customers", "orders",
            "profit", "transactions", "patients", "diagnosis"
        ],
        positive_descriptors=[
            "strong retention rates", "healthy workforce growth",
            "competitive compensation", "high performer ratio",
            "diverse workforce"
        ],
        negative_descriptors=[
            "high attrition", "compensation disparity",
            "workforce decline", "talent drain",
            "performance concerns"
        ],
        insight_questions=[
            "Which departments have the highest attrition?",
            "Is there a gender pay gap?",
            "How does tenure relate to performance?",
            "Which departments are overstaffed or understaffed?",
            "What is the compensation distribution?",
            "Are high performers being retained?",
        ],
    ),

    llm_context=(
        "This is an HR/workforce dataset. Focus on headcount distribution, "
        "compensation analysis, attrition patterns, gender diversity, "
        "tenure and performance metrics. "
        "NEVER refer to employees as 'customers' or salary as 'revenue'. "
        "Use HR/people analytics terminology."
    ),

    category_columns_hints=["department", "job_title", "gender", "education", "location"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 3: HEALTHCARE & MEDICAL
# ═══════════════════════════════════════════════════════════

HEALTHCARE_DOMAIN = DomainConfig(
    domain_id="healthcare",
    display_name="Healthcare & Medical",
    description="Patient data, hospital metrics, clinical data",
    icon="🏥",

    column_patterns=ColumnPatterns(patterns={
        "patient": [
            'patient', 'patient_id', 'mrn', 'case_id',
            'admission_id', 'encounter_id', 'subject_id'
        ],
        "diagnosis": [
            'diagnosis', 'condition', 'disease', 'icd',
            'icd_code', 'primary_diagnosis', 'medical_condition'
        ],
        "treatment_cost": [
            'cost', 'charge', 'bill', 'billing_amount',
            'total_charge', 'treatment_cost', 'hospital_bill',
            'amount', 'fee'
        ],
        "length_of_stay": [
            'los', 'length_of_stay', 'stay_duration',
            'days_admitted', 'hospital_days', 'duration'
        ],
        "department": [
            'department', 'ward', 'unit', 'specialty',
            'service_line', 'clinic'
        ],
        "outcome": [
            'outcome', 'result', 'status', 'discharge_status',
            'mortality', 'readmission', 'recovery'
        ],
        "age": [
            'age', 'patient_age', 'age_group', 'age_years'
        ],
        "gender": [
            'gender', 'sex', 'patient_gender'
        ],
        "insurance": [
            'insurance', 'payer', 'insurance_type',
            'coverage', 'plan', 'payor'
        ],
        "date": [
            'admission_date', 'discharge_date', 'visit_date',
            'date', 'encounter_date', 'appointment_date'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Patients", "total_patients", "Unique patient count", "{:,.0f}", "🏥", ["patient"]),
        KPIDefinition("Total Encounters", "total_encounters", "Total visits/admissions", "{:,.0f}", "📋", []),
        KPIDefinition("Avg Treatment Cost", "avg_treatment_cost", "Average cost per encounter", "${:,.0f}", "💰", ["treatment_cost"]),
        KPIDefinition("Total Charges", "total_charges", "Sum of all charges", "${:,.0f}", "💵", ["treatment_cost"]),
        KPIDefinition("Avg Length of Stay", "avg_los", "Average days admitted", "{:.1f} days", "📅", ["length_of_stay"]),
        KPIDefinition("Avg Patient Age", "avg_age", "Average patient age", "{:.0f} yrs", "🎂", ["age"]),
        KPIDefinition("Departments", "total_departments", "Unique departments/wards", "{:,.0f}", "🏢", ["department"]),
        KPIDefinition("Conditions", "total_conditions", "Unique diagnoses", "{:,.0f}", "🩺", ["diagnosis"]),
        KPIDefinition("Max Cost", "max_cost", "Highest single charge", "${:,.0f}", "🔝", ["treatment_cost"]),
        KPIDefinition("Cost Std Dev", "cost_std", "Cost variability", "${:,.0f}", "📊", ["treatment_cost"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="patient",
        primary_aggregation="count",

        secondary_metrics=[
            {"role": "treatment_cost", "aggregation": "mean", "label": "Avg Cost"},
            {"role": "treatment_cost", "aggregation": "sum", "label": "Total Charges"},
            {"role": "length_of_stay", "aggregation": "mean", "label": "Avg LOS"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="diagnosis",
                metric_role="patient",
                aggregation="count",
                title="Patient Count by Diagnosis",
                description="What are the most common conditions?"
            ),
            GroupByAnalysis(
                group_by_role="department",
                metric_role="patient",
                aggregation="count",
                title="Patient Count by Department",
                description="Department workload distribution"
            ),
            GroupByAnalysis(
                group_by_role="gender",
                metric_role="patient",
                aggregation="count",
                title="Patient Count by Gender",
                description="Gender distribution of patients"
            ),
            GroupByAnalysis(
                group_by_role="diagnosis",
                metric_role="treatment_cost",
                aggregation="mean",
                title="Average Treatment Cost by Diagnosis",
                show_percentage=False,
                description="Which conditions are most expensive to treat?"
            ),
            GroupByAnalysis(
                group_by_role="department",
                metric_role="length_of_stay",
                aggregation="mean",
                title="Average Length of Stay by Department",
                show_percentage=False,
                description="Which departments have longest stays?"
            ),
            GroupByAnalysis(
                group_by_role="insurance",
                metric_role="patient",
                aggregation="count",
                title="Patients by Insurance Type",
                description="Insurance coverage distribution"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="gender",
                col="diagnosis",
                value="patient",
                aggregation="count",
                title="Patient Count: Gender × Diagnosis",
                description="How does disease prevalence differ by gender?"
            ),
            CrossTabDefinition(
                row="department",
                col="diagnosis",
                value="patient",
                aggregation="count",
                title="Patient Count: Department × Diagnosis",
                description="Which departments handle which conditions?"
            ),
            CrossTabDefinition(
                row="gender",
                col="department",
                value="patient",
                aggregation="count",
                title="Patient Count: Gender × Department",
                description="Gender distribution across departments"
            ),
            CrossTabDefinition(
                row="diagnosis",
                col="outcome",
                value="patient",
                aggregation="count",
                title="Outcomes by Diagnosis",
                description="Recovery/mortality rates by condition"
            ),
        ],

        distribution_roles=["age", "treatment_cost", "length_of_stay"],

        correlation_pairs=[
            ("age", "treatment_cost"),
            ("age", "length_of_stay"),
            ("treatment_cost", "length_of_stay"),
        ],

        exclude_from_groupby=["patient", "date"],

        performer_metric_role="patient",
        performer_aggregation="count",
        performer_label="Most Common Conditions",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="bar",
            title="Patient Count by Diagnosis",
            x_role="diagnosis", y_role="patient",
            aggregation="count", priority=1,
            reason="Identify the most common medical conditions",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Patient Gender Distribution",
            x_role="gender", y_role="patient",
            aggregation="count", priority=2,
            reason="Show male/female patient ratio",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Patient Age Distribution",
            x_role="age", y_role=None,
            aggregation="raw", priority=3,
            reason="Understand patient demographics",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Patient Count by Department",
            x_role="department", y_role="patient",
            aggregation="count", priority=4,
            reason="Department workload comparison",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="grouped_bar",
            title="Diagnosis by Gender",
            x_role="diagnosis", y_role="patient",
            color_role="gender",
            aggregation="count", priority=5,
            reason="How disease prevalence differs by gender",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="box",
            title="Treatment Cost by Diagnosis",
            x_role="diagnosis", y_role="treatment_cost",
            aggregation="raw", priority=6,
            reason="Compare cost variability across conditions",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Length of Stay Distribution",
            x_role="length_of_stay", y_role=None,
            aggregation="raw", priority=7,
            reason="How long patients typically stay",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Patient Age vs Treatment Cost",
            x_role="age", y_role="treatment_cost",
            color_role="gender",
            aggregation="raw", priority=8,
            reason="Does age correlate with higher treatment costs?",
            section="relationships"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="patient",
        entity_plural="patients",
        primary_metric_name="patient count",
        primary_metric_verb="admitted",
        preferred_terms=[
            "patients", "admissions", "diagnosis", "treatment",
            "length of stay", "clinical outcomes", "department",
            "conditions", "encounters", "readmission",
            "healthcare utilization", "patient demographics"
        ],
        forbidden_terms=[
            "revenue", "sales", "customers", "orders",
            "profit", "transactions", "employees", "headcount",
            "attrition", "salary"
        ],
        positive_descriptors=[
            "improved patient outcomes", "reduced length of stay",
            "efficient resource utilization", "lower readmission rates",
            "cost-effective treatment"
        ],
        negative_descriptors=[
            "high readmission rates", "increased length of stay",
            "rising treatment costs", "capacity concerns",
            "outcome disparities"
        ],
        insight_questions=[
            "What are the most common diagnoses?",
            "How does patient volume differ by gender?",
            "Which conditions are most expensive to treat?",
            "Is there a relationship between age and length of stay?",
            "Which departments handle the most patients?",
            "Are there gender-based differences in diagnosis patterns?",
        ],
    ),

    llm_context=(
        "This is a healthcare/medical dataset. Focus on patient demographics, "
        "diagnosis distribution, treatment costs, length of stay patterns, "
        "department workload, and clinical outcomes. "
        "NEVER refer to patients as 'customers' or call treatment costs 'revenue'. "
        "ALWAYS count patients, not sum monetary values as the primary metric. "
        "Use clinical/healthcare analytics terminology."
    ),

    category_columns_hints=["diagnosis", "department", "gender", "outcome", "insurance"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 4: FINANCIAL & ACCOUNTING
# ═══════════════════════════════════════════════════════════

FINANCIAL_DOMAIN = DomainConfig(
    domain_id="financial",
    display_name="Financial & Accounting",
    description="Financial statements, budgets, expenses, invoices",
    icon="🏦",

    column_patterns=ColumnPatterns(patterns={
        "amount": [
            'amount', 'value', 'total', 'balance',
            'debit', 'credit', 'net_amount', 'gross_amount'
        ],
        "account": [
            'account', 'account_name', 'gl_account',
            'ledger', 'chart_of_accounts', 'account_type'
        ],
        "category": [
            'category', 'type', 'classification',
            'expense_type', 'income_type', 'line_item'
        ],
        "budget": [
            'budget', 'planned', 'forecast', 'estimated',
            'allocated', 'budgeted_amount'
        ],
        "actual": [
            'actual', 'realized', 'spent', 'incurred',
            'actual_amount'
        ],
        "department": [
            'department', 'cost_center', 'division',
            'business_unit'
        ],
        "period": [
            'period', 'fiscal_year', 'quarter', 'fiscal_period',
            'month', 'year'
        ],
        "date": [
            'date', 'transaction_date', 'posting_date',
            'invoice_date', 'payment_date'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Amount", "total_amount", "Sum of all amounts", "${:,.0f}", "💰", ["amount"]),
        KPIDefinition("Avg Transaction", "avg_transaction", "Average transaction size", "${:,.2f}", "💵", ["amount"]),
        KPIDefinition("Total Budget", "total_budget", "Total budgeted amount", "${:,.0f}", "📋", ["budget"]),
        KPIDefinition("Total Actual", "total_actual", "Total actual spend", "${:,.0f}", "💸", ["actual"]),
        KPIDefinition("Budget Variance", "budget_variance", "Actual vs Budget difference", "${:,.0f}", "📊", ["budget", "actual"]),
        KPIDefinition("Variance %", "variance_pct", "Variance as % of budget", "{:.1f}%", "📈", ["budget", "actual"]),
        KPIDefinition("Accounts", "total_accounts", "Unique accounts", "{:,.0f}", "📂", ["account"]),
        KPIDefinition("Categories", "total_categories", "Unique categories", "{:,.0f}", "🏷️", ["category"]),
        KPIDefinition("Transaction Count", "total_transactions", "Total records", "{:,.0f}", "🔢", []),
        KPIDefinition("Max Transaction", "max_transaction", "Largest single amount", "${:,.0f}", "🔝", ["amount"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="amount",
        primary_aggregation="sum",

        secondary_metrics=[
            {"role": "budget", "aggregation": "sum", "label": "Total Budget"},
            {"role": "actual", "aggregation": "sum", "label": "Total Actual"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="category",
                metric_role="amount",
                aggregation="sum",
                title="Total Amount by Category",
                description="Spending distribution across categories"
            ),
            GroupByAnalysis(
                group_by_role="account",
                metric_role="amount",
                aggregation="sum",
                title="Total Amount by Account",
                description="Which accounts have highest activity?"
            ),
            GroupByAnalysis(
                group_by_role="department",
                metric_role="amount",
                aggregation="sum",
                title="Spending by Department",
                description="Department-level spending comparison"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="category",
                col="department",
                value="amount",
                aggregation="sum",
                title="Spending: Category × Department",
                description="How spending categories vary by department"
            ),
        ],

        distribution_roles=["amount"],

        correlation_pairs=[
            ("budget", "actual"),
        ],

        exclude_from_groupby=["date"],

        performer_metric_role="amount",
        performer_aggregation="sum",
        performer_label="Highest Spend Categories",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="line",
            title="Financial Trend Over Time",
            x_role="date", y_role="amount",
            aggregation="sum", priority=1,
            reason="Track financial trajectory over time",
            section="trends"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Amount by Category",
            x_role="category", y_role="amount",
            aggregation="sum", priority=2,
            reason="Compare spending across categories",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Spending Share by Category",
            x_role="category", y_role="amount",
            aggregation="sum", priority=3,
            reason="Proportional spending breakdown",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Transaction Amount Distribution",
            x_role="amount", y_role=None,
            aggregation="raw", priority=4,
            reason="Understand transaction size patterns",
            section="distribution"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="transaction",
        entity_plural="transactions",
        primary_metric_name="amount",
        primary_metric_verb="recorded",
        preferred_terms=[
            "budget", "actual", "variance", "fiscal",
            "expenditure", "allocation", "cost center",
            "ledger", "accounts", "financial performance"
        ],
        forbidden_terms=[
            "patients", "employees", "customers", "diagnosis",
            "headcount", "attrition"
        ],
        positive_descriptors=[
            "under budget", "favorable variance", "cost savings",
            "efficient allocation"
        ],
        negative_descriptors=[
            "over budget", "unfavorable variance", "cost overrun",
            "budget deviation"
        ],
        insight_questions=[
            "Which categories are over budget?",
            "What is the overall budget variance?",
            "Are spending trends increasing or decreasing?",
        ],
    ),

    llm_context=(
        "This is financial/accounting data. Focus on budget vs actual analysis, "
        "expense categories, variance analysis, and cost management. "
        "Use financial/accounting terminology."
    ),

    category_columns_hints=["category", "account", "department", "cost_center", "type"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 5: E-COMMERCE & RETAIL
# ═══════════════════════════════════════════════════════════

ECOMMERCE_DOMAIN = DomainConfig(
    domain_id="ecommerce",
    display_name="E-Commerce & Retail",
    description="Online transactions, product sales, customer orders",
    icon="🛒",

    column_patterns=ColumnPatterns(patterns={
        "revenue": [
            'revenue', 'sales', 'amount', 'order_total',
            'total_price', 'transaction_amount', 'gmv',
            'price', 'subtotal', 'order_amount'
        ],
        "quantity": [
            'quantity', 'qty', 'units', 'items',
            'order_quantity', 'items_purchased'
        ],
        "product": [
            'product', 'item', 'sku', 'product_name',
            'item_name', 'product_title', 'product_id'
        ],
        "category": [
            'category', 'product_category', 'department',
            'type', 'segment', 'collection'
        ],
        "customer": [
            'customer', 'customer_id', 'user', 'user_id',
            'buyer', 'shopper', 'member_id'
        ],
        "channel": [
            'channel', 'source', 'platform', 'medium',
            'device', 'traffic_source', 'referral'
        ],
        "discount": [
            'discount', 'coupon', 'promo', 'discount_amount',
            'discount_pct', 'promotion'
        ],
        "rating": [
            'rating', 'review', 'stars', 'score',
            'satisfaction', 'feedback_score'
        ],
        "date": [
            'order_date', 'date', 'purchase_date',
            'transaction_date', 'created_at'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Revenue", "total_revenue", "Sum of all sales", "${:,.0f}", "💰", ["revenue"]),
        KPIDefinition("Total Orders", "total_orders", "Number of orders", "{:,.0f}", "📦", []),
        KPIDefinition("Avg Order Value", "avg_order_value", "Average revenue per order", "${:,.2f}", "💵", ["revenue"]),
        KPIDefinition("Total Units", "total_units", "Total items sold", "{:,.0f}", "📊", ["quantity"]),
        KPIDefinition("Unique Customers", "unique_customers", "Distinct customers", "{:,.0f}", "👥", ["customer"]),
        KPIDefinition("Revenue/Customer", "revenue_per_customer", "Avg spend per customer", "${:,.2f}", "💳", ["revenue", "customer"]),
        KPIDefinition("Avg Rating", "avg_rating", "Average product rating", "{:.1f} ⭐", "⭐", ["rating"]),
        KPIDefinition("Products", "total_products", "Unique products sold", "{:,.0f}", "🏷️", ["product"]),
        KPIDefinition("Categories", "total_categories", "Product categories", "{:,.0f}", "📂", ["category"]),
        KPIDefinition("Avg Discount", "avg_discount", "Average discount given", "${:,.2f}", "🏷️", ["discount"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="revenue",
        primary_aggregation="sum",

        secondary_metrics=[
            {"role": "quantity", "aggregation": "sum", "label": "Total Units"},
            {"role": "discount", "aggregation": "mean", "label": "Avg Discount"},
            {"role": "rating", "aggregation": "mean", "label": "Avg Rating"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="category",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Category",
                description="Which categories drive the most revenue?"
            ),
            GroupByAnalysis(
                group_by_role="product",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Product",
                description="Top-selling products"
            ),
            GroupByAnalysis(
                group_by_role="channel",
                metric_role="revenue",
                aggregation="sum",
                title="Revenue by Channel",
                description="Which channels perform best?"
            ),
            GroupByAnalysis(
                group_by_role="product",
                metric_role="rating",
                aggregation="mean",
                title="Average Rating by Product",
                show_percentage=False,
                description="Product quality comparison"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="category",
                col="channel",
                value="revenue",
                aggregation="sum",
                title="Revenue: Category × Channel",
                description="Which channels work best for which categories?"
            ),
        ],

        distribution_roles=["revenue", "quantity", "rating", "discount"],

        correlation_pairs=[
            ("revenue", "quantity"),
            ("revenue", "discount"),
            ("rating", "revenue"),
        ],

        exclude_from_groupby=["customer", "date"],

        performer_metric_role="revenue",
        performer_aggregation="sum",
        performer_label="Top Products",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="line",
            title="Revenue Trend Over Time",
            x_role="date", y_role="revenue",
            aggregation="sum", priority=1,
            reason="Track sales trajectory",
            section="trends"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Revenue by Category",
            x_role="category", y_role="revenue",
            aggregation="sum", priority=2,
            reason="Category performance comparison",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Revenue by Product (Top 10)",
            x_role="product", y_role="revenue",
            aggregation="sum", priority=3,
            reason="Identify bestselling products",
            section="comparison", max_categories=10
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Revenue Share by Channel",
            x_role="channel", y_role="revenue",
            aggregation="sum", priority=4,
            reason="Channel contribution to total sales",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Order Value Distribution",
            x_role="revenue", y_role=None,
            aggregation="raw", priority=5,
            reason="Understand spending patterns",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Price vs Rating",
            x_role="revenue", y_role="rating",
            aggregation="raw", priority=6,
            reason="Do higher-priced items get better ratings?",
            section="relationships"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="order",
        entity_plural="orders",
        primary_metric_name="revenue",
        primary_metric_verb="sold",
        preferred_terms=[
            "orders", "revenue", "customers", "products",
            "average order value", "conversion", "cart size",
            "channel", "category", "ratings"
        ],
        forbidden_terms=[
            "patients", "employees", "headcount", "diagnosis",
            "attrition", "salary", "clinical"
        ],
        positive_descriptors=[
            "strong sales growth", "healthy AOV",
            "high customer retention", "positive ratings"
        ],
        negative_descriptors=[
            "declining orders", "shrinking AOV",
            "high cart abandonment", "low ratings"
        ],
        insight_questions=[
            "Which products are bestsellers?",
            "What is the average order value trend?",
            "Which channels drive the most revenue?",
            "Are discounts impacting profitability?",
        ],
    ),

    llm_context=(
        "This is e-commerce/retail data. Focus on product performance, "
        "customer behavior, channel effectiveness, order values, and "
        "category trends. Use retail/e-commerce terminology."
    ),

    category_columns_hints=["category", "product", "channel", "region", "payment_method"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 6: OPERATIONS & SUPPLY CHAIN
# ═══════════════════════════════════════════════════════════

OPERATIONS_DOMAIN = DomainConfig(
    domain_id="operations",
    display_name="Operations & Supply Chain",
    description="Inventory, logistics, manufacturing, supply chain",
    icon="🏭",

    column_patterns=ColumnPatterns(patterns={
        "quantity": [
            'quantity', 'qty', 'units', 'stock',
            'inventory', 'on_hand', 'available',
            'produced', 'shipped', 'received'
        ],
        "cost": [
            'cost', 'unit_cost', 'total_cost',
            'manufacturing_cost', 'shipping_cost',
            'logistics_cost', 'procurement_cost'
        ],
        "lead_time": [
            'lead_time', 'delivery_time', 'transit_time',
            'cycle_time', 'processing_time', 'turnaround'
        ],
        "defect": [
            'defect', 'defect_rate', 'reject',
            'quality_issue', 'scrap', 'rework', 'failure'
        ],
        "supplier": [
            'supplier', 'vendor', 'manufacturer',
            'supplier_name', 'vendor_id', 'source'
        ],
        "warehouse": [
            'warehouse', 'location', 'facility',
            'plant', 'site', 'distribution_center', 'store'
        ],
        "product": [
            'product', 'item', 'sku', 'part',
            'component', 'material', 'part_number'
        ],
        "status": [
            'status', 'order_status', 'delivery_status',
            'fulfillment', 'state', 'condition'
        ],
        "date": [
            'date', 'order_date', 'ship_date',
            'delivery_date', 'production_date', 'received_date'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Units", "total_units", "Total quantity", "{:,.0f}", "📦", ["quantity"]),
        KPIDefinition("Total Cost", "total_cost", "Sum of all costs", "${:,.0f}", "💸", ["cost"]),
        KPIDefinition("Avg Unit Cost", "avg_unit_cost", "Average cost per unit", "${:,.2f}", "💰", ["cost"]),
        KPIDefinition("Avg Lead Time", "avg_lead_time", "Average delivery time", "{:.1f} days", "⏱️", ["lead_time"]),
        KPIDefinition("Defect Rate", "defect_rate", "Average defect rate", "{:.2f}%", "⚠️", ["defect"]),
        KPIDefinition("Suppliers", "total_suppliers", "Unique suppliers", "{:,.0f}", "🏭", ["supplier"]),
        KPIDefinition("Warehouses", "total_warehouses", "Unique locations", "{:,.0f}", "🏢", ["warehouse"]),
        KPIDefinition("Products", "total_products", "Unique products", "{:,.0f}", "🏷️", ["product"]),
        KPIDefinition("Total Records", "total_records", "Total data points", "{:,.0f}", "🔢", []),
        KPIDefinition("Cost Range", "cost_range", "Max minus Min cost", "${:,.0f}", "📊", ["cost"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="quantity",
        primary_aggregation="sum",

        secondary_metrics=[
            {"role": "cost", "aggregation": "sum", "label": "Total Cost"},
            {"role": "cost", "aggregation": "mean", "label": "Avg Unit Cost"},
            {"role": "lead_time", "aggregation": "mean", "label": "Avg Lead Time"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="supplier",
                metric_role="quantity",
                aggregation="sum",
                title="Units by Supplier",
                description="Which suppliers provide the most volume?"
            ),
            GroupByAnalysis(
                group_by_role="supplier",
                metric_role="cost",
                aggregation="mean",
                title="Average Cost by Supplier",
                show_percentage=False,
                description="Cost comparison across suppliers"
            ),
            GroupByAnalysis(
                group_by_role="warehouse",
                metric_role="quantity",
                aggregation="sum",
                title="Inventory by Warehouse",
                description="Stock distribution across locations"
            ),
            GroupByAnalysis(
                group_by_role="supplier",
                metric_role="lead_time",
                aggregation="mean",
                title="Average Lead Time by Supplier",
                show_percentage=False,
                description="Which suppliers deliver fastest?"
            ),
            GroupByAnalysis(
                group_by_role="status",
                metric_role="quantity",
                aggregation="count",
                title="Orders by Status",
                description="Order fulfillment status breakdown"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="supplier",
                col="product",
                value="quantity",
                aggregation="sum",
                title="Units: Supplier × Product",
                description="Product sourcing distribution"
            ),
            CrossTabDefinition(
                row="warehouse",
                col="status",
                value="quantity",
                aggregation="count",
                title="Order Status by Warehouse",
                description="Fulfillment performance by location"
            ),
        ],

        distribution_roles=["cost", "lead_time", "quantity"],

        correlation_pairs=[
            ("cost", "lead_time"),
            ("quantity", "cost"),
        ],

        exclude_from_groupby=["date"],

        performer_metric_role="quantity",
        performer_aggregation="sum",
        performer_label="Top Suppliers by Volume",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="bar",
            title="Units by Supplier",
            x_role="supplier", y_role="quantity",
            aggregation="sum", priority=1,
            reason="Compare supplier contribution",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Inventory by Warehouse",
            x_role="warehouse", y_role="quantity",
            aggregation="sum", priority=2,
            reason="Stock levels across locations",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="histogram",
            title="Lead Time Distribution",
            x_role="lead_time", y_role=None,
            aggregation="raw", priority=3,
            reason="Delivery time patterns",
            section="distribution"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Order Status Breakdown",
            x_role="status", y_role="quantity",
            aggregation="count", priority=4,
            reason="Fulfillment status overview",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="box",
            title="Cost by Supplier",
            x_role="supplier", y_role="cost",
            aggregation="raw", priority=5,
            reason="Cost variability across suppliers",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Cost vs Lead Time",
            x_role="cost", y_role="lead_time",
            color_role="supplier",
            aggregation="raw", priority=6,
            reason="Do cheaper suppliers take longer?",
            section="relationships"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="shipment",
        entity_plural="shipments",
        primary_metric_name="units",
        primary_metric_verb="processed",
        preferred_terms=[
            "supply chain", "logistics", "inventory", "lead time",
            "fulfillment", "procurement", "warehouse", "supplier",
            "throughput", "cycle time", "defect rate"
        ],
        forbidden_terms=[
            "patients", "employees", "salary", "diagnosis",
            "revenue", "customers"
        ],
        positive_descriptors=[
            "efficient fulfillment", "reduced lead times",
            "low defect rates", "optimized inventory"
        ],
        negative_descriptors=[
            "supply delays", "high defect rate",
            "inventory imbalance", "supplier bottleneck"
        ],
        insight_questions=[
            "Which suppliers have the best lead times?",
            "Is there a cost-quality tradeoff?",
            "Which warehouses are over/under capacity?",
        ],
    ),

    llm_context=(
        "This is operations/supply chain data. Focus on supplier performance, "
        "lead times, inventory levels, cost efficiency, and fulfillment rates. "
        "Use supply chain/operations terminology."
    ),

    category_columns_hints=["supplier", "warehouse", "product", "status", "category"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN 7: MARKETING & CAMPAIGNS
# ═══════════════════════════════════════════════════════════

MARKETING_DOMAIN = DomainConfig(
    domain_id="marketing",
    display_name="Marketing & Campaigns",
    description="Campaign performance, ad spend, conversions, leads",
    icon="📣",

    column_patterns=ColumnPatterns(patterns={
        "spend": [
            'spend', 'cost', 'budget', 'ad_spend',
            'investment', 'campaign_cost', 'media_spend',
            'amount'
        ],
        "impressions": [
            'impressions', 'views', 'reach', 'exposure',
            'eyeballs', 'displays'
        ],
        "clicks": [
            'clicks', 'click', 'visits', 'traffic',
            'sessions', 'page_views'
        ],
        "conversions": [
            'conversions', 'conversion', 'leads', 'signups',
            'registrations', 'purchases', 'actions', 'goals'
        ],
        "revenue": [
            'revenue', 'income', 'sales', 'earnings',
            'return', 'value'
        ],
        "campaign": [
            'campaign', 'campaign_name', 'campaign_id',
            'ad_group', 'initiative', 'program'
        ],
        "channel": [
            'channel', 'source', 'medium', 'platform',
            'network', 'ad_platform'
        ],
        "date": [
            'date', 'campaign_date', 'start_date',
            'report_date', 'period'
        ],
    }),

    kpi_definitions=[
        KPIDefinition("Total Spend", "total_spend", "Sum of all ad spend", "${:,.0f}", "💸", ["spend"]),
        KPIDefinition("Total Impressions", "total_impressions", "Sum of all impressions", "{:,.0f}", "👁️", ["impressions"]),
        KPIDefinition("Total Clicks", "total_clicks", "Sum of all clicks", "{:,.0f}", "🖱️", ["clicks"]),
        KPIDefinition("Total Conversions", "total_conversions", "Sum of all conversions", "{:,.0f}", "🎯", ["conversions"]),
        KPIDefinition("CTR", "ctr", "Click-through rate", "{:.2f}%", "📊", ["clicks", "impressions"]),
        KPIDefinition("CPC", "cpc", "Cost per click", "${:,.2f}", "💰", ["spend", "clicks"]),
        KPIDefinition("CPL", "cpl", "Cost per lead/conversion", "${:,.2f}", "💵", ["spend", "conversions"]),
        KPIDefinition("Conversion Rate", "conversion_rate", "Clicks to conversion", "{:.2f}%", "📈", ["conversions", "clicks"]),
        KPIDefinition("ROAS", "roas", "Return on ad spend", "{:.2f}x", "🔄", ["revenue", "spend"]),
        KPIDefinition("Campaigns", "total_campaigns", "Unique campaigns", "{:,.0f}", "📣", ["campaign"]),
    ],

    analysis_config=AnalysisConfig(
        primary_metric_role="spend",
        primary_aggregation="sum",

        secondary_metrics=[
            {"role": "impressions", "aggregation": "sum", "label": "Total Impressions"},
            {"role": "clicks", "aggregation": "sum", "label": "Total Clicks"},
            {"role": "conversions", "aggregation": "sum", "label": "Total Conversions"},
        ],

        group_by_analyses=[
            GroupByAnalysis(
                group_by_role="campaign",
                metric_role="spend",
                aggregation="sum",
                title="Spend by Campaign",
                description="Budget allocation across campaigns"
            ),
            GroupByAnalysis(
                group_by_role="channel",
                metric_role="spend",
                aggregation="sum",
                title="Spend by Channel",
                description="Channel-level investment"
            ),
            GroupByAnalysis(
                group_by_role="campaign",
                metric_role="conversions",
                aggregation="sum",
                title="Conversions by Campaign",
                description="Which campaigns drive the most conversions?"
            ),
            GroupByAnalysis(
                group_by_role="channel",
                metric_role="clicks",
                aggregation="sum",
                title="Clicks by Channel",
                description="Traffic generation by channel"
            ),
        ],

        cross_tabs=[
            CrossTabDefinition(
                row="channel",
                col="campaign",
                value="conversions",
                aggregation="sum",
                title="Conversions: Channel × Campaign",
                description="Which channel-campaign combos convert best?"
            ),
        ],

        distribution_roles=["spend", "clicks", "conversions"],

        correlation_pairs=[
            ("spend", "conversions"),
            ("spend", "clicks"),
            ("clicks", "conversions"),
            ("impressions", "clicks"),
        ],

        exclude_from_groupby=["date"],

        performer_metric_role="conversions",
        performer_aggregation="sum",
        performer_label="Top Converting Campaigns",
    ),

    chart_specs=[
        DomainChartSpec(
            chart_type="bar",
            title="Spend by Campaign",
            x_role="campaign", y_role="spend",
            aggregation="sum", priority=1,
            reason="Budget allocation overview",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="bar",
            title="Conversions by Campaign",
            x_role="campaign", y_role="conversions",
            aggregation="sum", priority=2,
            reason="Campaign effectiveness comparison",
            section="comparison"
        ),
        DomainChartSpec(
            chart_type="pie",
            title="Spend Share by Channel",
            x_role="channel", y_role="spend",
            aggregation="sum", priority=3,
            reason="Channel investment distribution",
            section="composition"
        ),
        DomainChartSpec(
            chart_type="scatter",
            title="Spend vs Conversions",
            x_role="spend", y_role="conversions",
            color_role="channel",
            aggregation="raw", priority=4,
            reason="Is more spend driving more conversions?",
            section="relationships"
        ),
        DomainChartSpec(
            chart_type="line",
            title="Campaign Performance Over Time",
            x_role="date", y_role="conversions",
            aggregation="sum", priority=5,
            reason="Conversion trends over time",
            section="trends"
        ),
        DomainChartSpec(
            chart_type="grouped_bar",
            title="Clicks & Conversions by Channel",
            x_role="channel", y_role="clicks",
            color_role="campaign",
            aggregation="sum", priority=6,
            reason="Channel-level funnel comparison",
            section="comparison"
        ),
    ],

    vocabulary=DomainVocabulary(
        entity_name="campaign",
        entity_plural="campaigns",
        primary_metric_name="ad spend",
        primary_metric_verb="invested",
        preferred_terms=[
            "campaigns", "impressions", "clicks", "conversions",
            "CTR", "CPC", "ROAS", "funnel", "channel",
            "ad spend", "cost per acquisition", "engagement"
        ],
        forbidden_terms=[
            "patients", "employees", "salary", "diagnosis",
            "headcount", "attrition", "inventory"
        ],
        positive_descriptors=[
            "high conversion rate", "strong ROAS",
            "efficient CPC", "growing engagement"
        ],
        negative_descriptors=[
            "low CTR", "poor conversion rate",
            "declining ROAS", "wasted ad spend"
        ],
        insight_questions=[
            "Which campaign has the best conversion rate?",
            "What is the ROAS by channel?",
            "Are we spending efficiently?",
            "Which channels should we invest more in?",
        ],
    ),

    llm_context=(
        "This is marketing/campaign data. Focus on campaign ROI, "
        "conversion rates, channel performance, spend efficiency, "
        "and funnel metrics (impressions→clicks→conversions). "
        "Use digital marketing terminology."
    ),

    category_columns_hints=["campaign", "channel", "source", "medium", "ad_group"],
)


# ═══════════════════════════════════════════════════════════
# DOMAIN REGISTRY
# ═══════════════════════════════════════════════════════════

DOMAIN_REGISTRY: Dict[str, Optional[DomainConfig]] = {
    "auto":        None,
    "sales":       SALES_DOMAIN,
    "ecommerce":   ECOMMERCE_DOMAIN,
    "hr":          HR_DOMAIN,
    "financial":   FINANCIAL_DOMAIN,
    "healthcare":  HEALTHCARE_DOMAIN,
    "operations":  OPERATIONS_DOMAIN,
    "marketing":   MARKETING_DOMAIN,
}


def get_domain_options() -> Dict[str, str]:
    """Returns dict for Streamlit dropdown"""
    options = {"🔍 Auto Detect": "auto"}
    for domain_id, config in DOMAIN_REGISTRY.items():
        if config is not None:
            options[f"{config.icon} {config.display_name}"] = domain_id
    return options


def get_domain_config(domain_id: str) -> Optional[DomainConfig]:
    """Get config for a specific domain"""
    return DOMAIN_REGISTRY.get(domain_id)