# -*- coding: utf-8 -*-
"""smart_kpi_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1EVe6SmJ6wn-5m0p-PKclMEf6RzdIZA
"""

# src/analysis/smart_kpi_calculator.py

"""
DOMAIN-AWARE KPI CALCULATOR
────────────────────────────
Replaces the old KPICalculator with domain-specific logic.

OLD APPROACH: Guess column meanings from names → often wrong
NEW APPROACH: User selects domain → system knows exactly what to look for

If user selects "Auto Detect", falls back to best-guess logic.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Tuple
from src.analysis.domain_config import (
    DomainConfig, DOMAIN_REGISTRY, SALES_DOMAIN,
    get_domain_config
)
from src.utils.logger import logger


class SmartKPICalculator:
    """
    Calculates KPIs based on the selected business domain.

    Usage:
        calc = SmartKPICalculator(domain_id="hr")
        results = calc.calculate(df)
    """

    def __init__(self, domain_id: str = "auto"):
        """
        Parameters:
        -----------
        domain_id : str
            The business domain selected by user.
            Options: 'auto', 'sales', 'hr', 'financial',
                     'healthcare', 'ecommerce', 'operations', 'marketing'
        """
        self.domain_id = domain_id

        if domain_id == "auto":
            self.domain_config = None   # will be determined later
        else:
            self.domain_config = get_domain_config(domain_id)
            if self.domain_config is None:
                logger.warning(f"Unknown domain '{domain_id}', falling back to auto")


    def calculate(self, df: pd.DataFrame) -> Dict:
        """
        Main entry point: detect columns → calculate KPIs.
        """

        logger.info(f"Calculating KPIs for domain: {self.domain_id}")

        # Step 1: If auto-detect, try to figure out the domain
        if self.domain_config is None:
            self.domain_config = self._auto_detect_domain(df)
            self.domain_id = self.domain_config.domain_id
            logger.info(f"Auto-detected domain: {self.domain_id}")

        # Step 2: Map columns to metric roles using domain patterns
        column_mapping = self._map_columns(df)
        logger.info(f"Column mapping: {column_mapping}")

        # Step 3: Calculate each defined KPI
        kpis = self._calculate_kpis(df, column_mapping)

        # Step 4: Category breakdowns
        category_breakdown = self._category_breakdown(df, column_mapping)

        return {
            "domain": self.domain_id,
            "domain_name": self.domain_config.display_name,
            "domain_icon": self.domain_config.icon,
            "domain_description": self.domain_config.description,
            "llm_context": self.domain_config.llm_context,
            "column_mapping": column_mapping,
            "kpis": kpis,
            "kpi_definitions": [
                {
                    "name": kd.name,
                    "key": kd.key,
                    "icon": kd.icon,
                    "format": kd.format,
                    "description": kd.description,
                }
                for kd in self.domain_config.kpi_definitions
                if kd.key in kpis
            ],
            "category_breakdown": category_breakdown,
            "unmapped_columns": self._get_unmapped_columns(df, column_mapping),
        }


    def _map_columns(self, df: pd.DataFrame) -> Dict[str, str]:
        """
        Map DataFrame columns to domain metric roles.

        Returns:
            Dict where key = metric_role, value = column_name
            Example: {"compensation": "salary", "department": "dept_name"}
        """

        mapping = {}
        used_columns = set()

        patterns = self.domain_config.column_patterns.patterns

        for metric_role, pattern_list in patterns.items():
            for col in df.columns:
                if col in used_columns:
                    continue

                col_lower = col.lower().strip().replace(' ', '_')

                for pattern in pattern_list:
                    if pattern in col_lower:
                        # Validate: numeric roles need numeric columns
                        numeric_roles = self._get_numeric_roles()

                        if metric_role in numeric_roles:
                            if pd.api.types.is_numeric_dtype(df[col]):
                                mapping[metric_role] = col
                                used_columns.add(col)
                                break
                        else:
                            mapping[metric_role] = col
                            used_columns.add(col)
                            break

        return mapping


    def _get_numeric_roles(self) -> set:
        """Which metric roles require numeric columns?"""
        numeric_keywords = {
            'revenue', 'cost', 'quantity', 'profit', 'compensation',
            'tenure', 'performance', 'age', 'amount', 'budget',
            'actual', 'variance', 'treatment_cost', 'length_of_stay',
            'lead_time', 'defect', 'spend', 'impressions', 'clicks',
            'conversions', 'discount', 'rating'
        }
        return numeric_keywords


    def _calculate_kpis(self, df: pd.DataFrame,
                         column_mapping: Dict) -> Dict:
        """Calculate all KPIs defined for this domain"""

        kpis = {}

        for kpi_def in self.domain_config.kpi_definitions:
            try:
                value = self._compute_single_kpi(df, column_mapping, kpi_def)
                if value is not None:
                    kpis[kpi_def.key] = value
            except Exception as e:
                logger.warning(f"Failed to calculate KPI '{kpi_def.key}': {e}")

        return kpis


    def _compute_single_kpi(self, df: pd.DataFrame,
                             mapping: Dict, kpi_def) -> Optional[float]:
        """
        Compute a single KPI value.

        This is the CORE logic — each KPI has its own formula.
        """

        key = kpi_def.key
        requires = kpi_def.requires

        # Check if required columns are available
        for req in requires:
            if req not in mapping:
                return None

        # ── UNIVERSAL KPIs (work for any domain) ────────
        if key == "total_records" or key == "total_transactions" or key == "total_encounters" or key == "total_orders":
            return len(df)

        if key == "total_headcount":
            return len(df)

        # ── REVENUE / AMOUNT KPIs ───────────────────────
        if key == "total_revenue" or key == "total_amount" or key == "total_payroll":
            col = mapping.get(requires[0])
            return round(float(df[col].sum()), 2)

        if key in ["avg_order_value", "avg_transaction", "avg_salary",
                    "avg_treatment_cost", "avg_unit_cost"]:
            col = mapping.get(requires[0])
            return round(float(df[col].mean()), 2)

        if key in ["median_salary", "median_revenue"]:
            col = mapping.get(requires[0])
            return round(float(df[col].median()), 2)

        if key in ["max_transaction", "max_cost"]:
            col = mapping.get(requires[0])
            return round(float(df[col].max()), 2)

        if key in ["salary_range", "cost_range"]:
            col = mapping.get(requires[0])
            return round(float(df[col].max() - df[col].min()), 2)

        if key in ["cost_std"]:
            col = mapping.get(requires[0])
            return round(float(df[col].std()), 2)

        # ── COST KPIs ──────────────────────────────────
        if key == "total_cost" or key == "total_spend":
            col = mapping.get(requires[0])
            return round(float(df[col].sum()), 2)

        # ── QUANTITY KPIs ──────────────────────────────
        if key == "total_units":
            col = mapping.get(requires[0])
            return round(float(df[col].sum()), 0)

        if key == "total_impressions" or key == "total_clicks" or key == "total_conversions":
            col = mapping.get(requires[0])
            return round(float(df[col].sum()), 0)

        # ── PROFIT KPIs ────────────────────────────────
        if key == "gross_profit":
            rev_col = mapping.get("revenue")
            cost_col = mapping.get("cost")
            return round(float(df[rev_col].sum() - df[cost_col].sum()), 2)

        if key == "profit_margin_pct":
            rev_col = mapping.get("revenue")
            cost_col = mapping.get("cost")
            total_rev = df[rev_col].sum()
            if total_rev == 0:
                return 0
            profit = total_rev - df[cost_col].sum()
            return round(float((profit / total_rev) * 100), 1)

        # ── CALCULATED RATIOS ──────────────────────────
        if key == "avg_price_per_unit":
            rev_col = mapping.get("revenue")
            qty_col = mapping.get("quantity")
            total_qty = df[qty_col].sum()
            return round(float(df[rev_col].sum() / total_qty), 2) if total_qty > 0 else 0

        if key == "revenue_per_customer":
            rev_col = mapping.get("revenue")
            cust_col = mapping.get("customer")
            n_customers = df[cust_col].nunique()
            return round(float(df[rev_col].sum() / n_customers), 2) if n_customers > 0 else 0

        # ── COUNT UNIQUE KPIs ──────────────────────────
        if key in ["unique_customers", "total_patients"]:
            col = mapping.get(requires[0])
            return int(df[col].nunique())

        if key in ["total_departments", "total_suppliers",
                    "total_warehouses", "total_products",
                    "total_categories", "total_campaigns",
                    "total_conditions", "total_accounts"]:
            col = mapping.get(requires[0])
            return int(df[col].nunique())

        # ── AVERAGE KPIs ──────────────────────────────
        if key in ["avg_tenure", "avg_performance", "avg_age",
                    "avg_los", "avg_lead_time", "avg_discount",
                    "avg_rating"]:
            col = mapping.get(requires[0])
            return round(float(df[col].mean()), 2)

        # ── RATE KPIs ─────────────────────────────────
        if key == "attrition_rate":
            col = mapping.get("attrition")
            series = df[col].dropna()
            # Try to detect binary (Yes/No, 1/0, True/False)
            if series.dtype in ['int64', 'float64']:
                return round(float(series.mean() * 100), 1)
            else:
                # Count "Yes", "Left", "Terminated", etc.
                positive_values = ['yes', 'left', 'terminated',
                                   'resigned', 'churned', '1', 'true']
                attrition_count = series.str.lower().isin(positive_values).sum()
                return round(float(attrition_count / len(series) * 100), 1)

        if key == "defect_rate":
            col = mapping.get("defect")
            return round(float(df[col].mean()), 2)

        # ── MARKETING CALCULATED KPIs ─────────────────
        if key == "ctr":   # Click-through rate
            clicks_col = mapping.get("clicks")
            impressions_col = mapping.get("impressions")
            total_imp = df[impressions_col].sum()
            return round(float(df[clicks_col].sum() / total_imp * 100), 2) if total_imp > 0 else 0

        if key == "cpc":   # Cost per click
            spend_col = mapping.get("spend")
            clicks_col = mapping.get("clicks")
            total_clicks = df[clicks_col].sum()
            return round(float(df[spend_col].sum() / total_clicks), 2) if total_clicks > 0 else 0

        if key == "cpl":   # Cost per lead
            spend_col = mapping.get("spend")
            conv_col = mapping.get("conversions")
            total_conv = df[conv_col].sum()
            return round(float(df[spend_col].sum() / total_conv), 2) if total_conv > 0 else 0

        if key == "conversion_rate":
            conv_col = mapping.get("conversions")
            clicks_col = mapping.get("clicks")
            total_clicks = df[clicks_col].sum()
            return round(float(df[conv_col].sum() / total_clicks * 100), 2) if total_clicks > 0 else 0

        if key == "roas":   # Return on Ad Spend
            rev_col = mapping.get("revenue")
            spend_col = mapping.get("spend")
            total_spend = df[spend_col].sum()
            return round(float(df[rev_col].sum() / total_spend), 2) if total_spend > 0 else 0

        # ── BUDGET KPIs ───────────────────────────────
        if key == "total_budget":
            col = mapping.get("budget")
            return round(float(df[col].sum()), 2)

        if key == "total_actual":
            col = mapping.get("actual")
            return round(float(df[col].sum()), 2)

        if key == "budget_variance":
            budget_col = mapping.get("budget")
            actual_col = mapping.get("actual")
            return round(float(df[actual_col].sum() - df[budget_col].sum()), 2)

        if key == "variance_pct":
            budget_col = mapping.get("budget")
            actual_col = mapping.get("actual")
            total_budget = df[budget_col].sum()
            if total_budget == 0:
                return 0
            variance = df[actual_col].sum() - total_budget
            return round(float((variance / total_budget) * 100), 1)

        return None


    def _category_breakdown(self, df: pd.DataFrame,
                             column_mapping: Dict) -> Dict:
        """Break down primary metric by categorical columns"""

        # Find the primary metric column for this domain
        primary_metric = self._get_primary_metric_col(column_mapping)
        if primary_metric is None:
            return {}

        # Find categorical columns using domain hints
        cat_columns = self._find_category_columns(df)
        breakdowns = {}

        for cat_col in cat_columns[:3]:    # limit to top 3
            if df[cat_col].nunique() > 20 or df[cat_col].nunique() < 2:
                continue

            grouped = (
                df.groupby(cat_col)[primary_metric]
                .agg(['sum', 'mean', 'count'])
                .sort_values('sum', ascending=False)
            )

            total = grouped['sum'].sum()

            breakdowns[cat_col] = {
                "metric": primary_metric,
                "data": [
                    {
                        "name": str(idx),
                        "total": round(float(row['sum']), 2),
                        "average": round(float(row['mean']), 2),
                        "count": int(row['count']),
                        "pct_share": round(float(row['sum'] / total * 100), 1) if total > 0 else 0,
                    }
                    for idx, row in grouped.iterrows()
                ],
                "insight": self._make_insight(grouped, cat_col, total),
            }

        return breakdowns


    def _get_primary_metric_col(self, mapping: Dict) -> Optional[str]:
        """Get the main numeric column for breakdowns"""

        # Priority order by domain type
        priority_roles = [
            'revenue', 'compensation', 'amount', 'treatment_cost',
            'spend', 'cost', 'quantity'
        ]

        for role in priority_roles:
            if role in mapping:
                return mapping[role]

        return None


    def _find_category_columns(self, df: pd.DataFrame) -> List[str]:
        """Find categorical columns, prioritizing domain hints"""

        cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
        hints = self.domain_config.category_columns_hints

        # Sort: columns matching hints come first
        def sort_key(col):
            col_lower = col.lower()
            for i, hint in enumerate(hints):
                if hint in col_lower:
                    return i
            return 999

        cat_cols.sort(key=sort_key)
        return cat_cols


    def _make_insight(self, grouped, cat_col, total) -> str:
        """Generate one-line insight"""

        top = grouped.index[0]
        top_pct = round(grouped['sum'].iloc[0] / total * 100, 1) if total > 0 else 0
        bottom = grouped.index[-1]
        bottom_pct = round(grouped['sum'].iloc[-1] / total * 100, 1) if total > 0 else 0

        return (
            f"'{top}' leads with {top_pct}% of total, "
            f"while '{bottom}' has the lowest at {bottom_pct}%."
        )


    def _get_unmapped_columns(self, df: pd.DataFrame,
                               mapping: Dict) -> List[str]:
        """Find columns that weren't mapped to any role"""
        mapped_cols = set(mapping.values())
        return [col for col in df.columns if col not in mapped_cols]


    def _auto_detect_domain(self, df: pd.DataFrame) -> DomainConfig:
        """
        Try to auto-detect the domain by scoring each domain's
        column patterns against the actual columns.

        Returns the domain with the highest match score.
        """

        scores = {}
        columns_lower = [col.lower().strip() for col in df.columns]

        for domain_id, config in DOMAIN_REGISTRY.items():
            if config is None:    # skip "auto"
                continue

            score = 0
            for metric_role, patterns in config.column_patterns.patterns.items():
                for col in columns_lower:
                    for pattern in patterns:
                        if pattern in col:
                            score += 1
                            break

            scores[domain_id] = score

        # Pick highest scoring domain
        if scores:
            best_domain = max(scores, key=scores.get)
            best_score = scores[best_domain]
            logger.info(f"Auto-detect scores: {scores}")
            logger.info(f"Best match: {best_domain} (score: {best_score})")

            if best_score > 0:
                return DOMAIN_REGISTRY[best_domain]

        # Fallback to sales (most generic)
        logger.warning("Could not auto-detect domain, defaulting to Sales")
        return SALES_DOMAIN