# -*- coding: utf-8 -*-
"""trend_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/analysis/trend_detector.py

"""
TREND DETECTION MODULE
──────────────────────
Detects time-based patterns in the data.

WHAT IT CALCULATES:
1. Period-over-period growth (MoM, QoQ, YoY)
2. Overall trend direction (upward / downward / flat)
3. Best & worst performing periods
4. Moving averages (smoothed trend line)
5. Consecutive growth/decline streaks
6. Seasonality detection
7. Acceleration/deceleration of growth

WHY THIS IS YOUR DIFFERENTIATOR:
As a Data Analyst, you KNOW what good trend analysis looks like.
Most GenAI projects just call an LLM and hope for the best.
YOUR project does REAL analysis first, then lets LLM narrate it.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Tuple
from src.utils.logger import logger


class TrendDetector:
    """
    Detects and analyzes time-based trends in data.

    Usage:
        detector = TrendDetector()
        trends = detector.analyze(
            df=dataframe,
            date_col="order_date",       # optional, auto-detected
            value_col="revenue",          # optional, auto-detected
            freq="M"                      # M=monthly, W=weekly, Q=quarterly
        )
    """

    # Frequency display names for reports
    FREQ_NAMES = {
        'D': 'Daily',
        'W': 'Weekly',
        'M': 'Monthly',
        'Q': 'Quarterly',
        'Y': 'Yearly',
    }

    def analyze(self,
                df: pd.DataFrame,
                date_col: Optional[str] = None,
                value_col: Optional[str] = None,
                freq: Optional[str] = None) -> Dict:
        """
        Main entry point for trend analysis.

        Parameters:
        -----------
        df : pd.DataFrame
            The dataset
        date_col : str, optional
            Date column name. Auto-detected if not provided.
        value_col : str, optional
            Numeric column to analyze trends for.
            Auto-detected if not provided (picks revenue/salary/amount etc.)
        freq : str, optional
            Resampling frequency. Auto-determined based on date range.
            'D'=daily, 'W'=weekly, 'M'=monthly, 'Q'=quarterly

        Returns:
        --------
        Dict with all trend analysis results
        """

        logger.info("Starting trend analysis...")

        # ── Step 1: Find date column ────────────────────
        if date_col is None:
            date_col = self._find_date_column(df)

        if date_col is None:
            logger.warning("No date column found — skipping trend analysis")
            return {
                "available": False,
                "reason": "No datetime column found in the dataset. "
                          "Trend analysis requires a date/time column."
            }

        # ── Step 2: Find value column ───────────────────
        if value_col is None:
            value_col = self._find_best_value_column(df, date_col)

        if value_col is None:
            logger.warning("No numeric column found for trends")
            return {
                "available": False,
                "reason": "No suitable numeric column found for trend analysis."
            }

        # ── Step 3: Determine frequency ─────────────────
        if freq is None:
            freq = self._auto_frequency(df, date_col)

        logger.info(f"Trend analysis: date='{date_col}', "
                    f"value='{value_col}', freq='{freq}'")

        # ── Step 4: Prepare time series ─────────────────
        time_series = self._prepare_time_series(df, date_col, value_col, freq)

        if time_series is None or len(time_series) < 3:
            return {
                "available": False,
                "reason": f"Not enough time periods for analysis "
                          f"(need at least 3, got {len(time_series) if time_series is not None else 0})"
            }

        # ── Step 5: Run all trend analyses ──────────────
        results = {
            "available": True,
            "config": {
                "date_column": date_col,
                "value_column": value_col,
                "frequency": freq,
                "frequency_name": self.FREQ_NAMES.get(freq, freq),
                "periods_analyzed": len(time_series),
            },
            "time_series_data": self._series_to_dict(time_series),
            "overall_trend": self._overall_trend(time_series),
            "growth_analysis": self._growth_analysis(time_series),
            "period_comparison": self._period_comparison(time_series),
            "best_worst_periods": self._best_worst_periods(time_series),
            "moving_averages": self._moving_averages(time_series),
            "momentum": self._momentum_analysis(time_series),
            "seasonality": self._seasonality_check(time_series, freq),
        }

        # ── Step 6: Multi-metric trends (if applicable) ─
        other_numeric_cols = [
            col for col in df.select_dtypes(include=[np.number]).columns
            if col != value_col
        ]
        if other_numeric_cols:
            results["secondary_trends"] = self._secondary_trends(
                df, date_col, other_numeric_cols[:3], freq
            )

        logger.info("Trend analysis complete")
        return results


    # ═══════════════════════════════════════════════════════
    # COLUMN DETECTION HELPERS
    # ═══════════════════════════════════════════════════════

    def _find_date_column(self, df: pd.DataFrame) -> Optional[str]:
        """Find the best date column in the DataFrame"""

        # Strategy 1: Look for datetime dtype columns
        datetime_cols = df.select_dtypes(include=['datetime64']).columns
        if len(datetime_cols) > 0:
            return datetime_cols[0]

        # Strategy 2: Look for column names with date-like words
        date_keywords = ['date', 'time', 'datetime', 'timestamp',
                         'created', 'month', 'year', 'period']

        for col in df.columns:
            col_lower = col.lower().strip()
            for keyword in date_keywords:
                if keyword in col_lower:
                    # Try to parse it
                    try:
                        pd.to_datetime(df[col].head(10))
                        return col
                    except (ValueError, TypeError):
                        pass

        return None


    def _find_best_value_column(self, df: pd.DataFrame,
                                 date_col: str) -> Optional[str]:
        """
        Find the most appropriate numeric column for trend analysis.

        Priority:
        1. Revenue/Sales columns
        2. Amount/Total columns
        3. Salary/Compensation columns
        4. Cost columns
        5. First numeric column found
        """

        numeric_cols = [
            col for col in df.select_dtypes(include=[np.number]).columns
            if col != date_col
        ]

        if not numeric_cols:
            return None

        # Priority patterns
        priority_patterns = [
            ['revenue', 'sales', 'income', 'turnover', 'gmv'],
            ['amount', 'total', 'value', 'price'],
            ['salary', 'compensation', 'pay', 'wage'],
            ['cost', 'expense', 'spend'],
            ['quantity', 'qty', 'units', 'count'],
            ['profit', 'margin', 'earnings'],
        ]

        for patterns in priority_patterns:
            for col in numeric_cols:
                col_lower = col.lower()
                if any(p in col_lower for p in patterns):
                    return col

        # Fallback: column with highest variance (most interesting to trend)
        variances = {col: df[col].var() for col in numeric_cols}
        return max(variances, key=variances.get)


    def _auto_frequency(self, df: pd.DataFrame, date_col: str) -> str:
        """
        Automatically determine the best resampling frequency.

        Logic:
        - < 30 days of data   → Daily ('D')
        - 30 to 180 days      → Weekly ('W')
        - 180 days to 3 years → Monthly ('M')
        - > 3 years           → Quarterly ('Q')

        WHY AUTO-FREQUENCY?
        If someone uploads 7 days of data and we resample monthly,
        we'd get 1 data point — useless.
        If someone uploads 5 years of daily data and we keep daily,
        the chart would be unreadable.
        """

        dates = pd.to_datetime(df[date_col])
        date_range_days = (dates.max() - dates.min()).days

        if date_range_days < 30:
            return 'D'
        elif date_range_days < 180:
            return 'W'
        elif date_range_days < 1095:   # ~3 years
            return 'M'
        else:
            return 'Q'


    # ═══════════════════════════════════════════════════════
    # CORE ANALYSIS METHODS
    # ═══════════════════════════════════════════════════════

    def _prepare_time_series(self, df: pd.DataFrame,
                              date_col: str, value_col: str,
                              freq: str) -> Optional[pd.Series]:
        """
        Convert raw data into a clean time series.

        Steps:
        1. Parse dates
        2. Set date as index
        3. Resample to desired frequency (sum values)
        4. Sort chronologically
        5. Handle missing periods (fill with 0)
        """

        try:
            temp_df = df[[date_col, value_col]].copy()
            temp_df[date_col] = pd.to_datetime(temp_df[date_col], errors='coerce')
            temp_df = temp_df.dropna(subset=[date_col, value_col])

            # Set date as index and resample
            temp_df = temp_df.set_index(date_col)
            resampled = temp_df[value_col].resample(freq).sum()

            # Fill missing periods with 0
            # WHY? If there are no sales in February, it should show 0
            # not skip February entirely
            resampled = resampled.fillna(0)

            # Sort by date
            resampled = resampled.sort_index()

            # Name the series for later reference
            resampled.name = value_col

            return resampled

        except Exception as e:
            logger.error(f"Error preparing time series: {e}")
            return None


    def _overall_trend(self, series: pd.Series) -> Dict:
        """
        Determine overall trend direction using linear regression.

        HOW:
        Fit a straight line through the data points.
        If slope > 0 → upward trend
        If slope < 0 → downward trend
        If slope ≈ 0 → flat/stable

        Also calculates R² (how well the line fits).
        High R² = consistent trend
        Low R² = volatile/no clear trend
        """

        x = np.arange(len(series))
        y = series.values.astype(float)

        # Linear regression: y = slope * x + intercept
        slope, intercept = np.polyfit(x, y, 1)

        # R-squared (coefficient of determination)
        y_pred = slope * x + intercept
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - np.mean(y)) ** 2)
        r_squared = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0

        # Trend classification
        # Use slope relative to mean to determine significance
        mean_val = np.mean(y)
        if mean_val == 0:
            relative_slope = 0
        else:
            relative_slope = (slope / mean_val) * 100   # slope as % of mean

        if relative_slope > 2:
            direction = "upward"
            emoji = "📈"
            description = "showing consistent growth"
        elif relative_slope < -2:
            direction = "downward"
            emoji = "📉"
            description = "showing a declining pattern"
        else:
            direction = "stable"
            emoji = "➡️"
            description = "remaining relatively flat"

        # Trend strength
        if abs(r_squared) > 0.7:
            strength = "strong"
        elif abs(r_squared) > 0.4:
            strength = "moderate"
        else:
            strength = "weak"

        return {
            "direction": direction,
            "emoji": emoji,
            "strength": strength,
            "slope": round(float(slope), 2),
            "slope_per_period": round(float(slope), 2),
            "relative_slope_pct": round(float(relative_slope), 2),
            "r_squared": round(float(r_squared), 3),
            "intercept": round(float(intercept), 2),
            "description": description,
            "interpretation": (
                f"{series.name or 'Value'} is {description} "
                f"with a {strength} {direction} trend. "
                f"On average, it changes by {abs(round(slope, 2)):,} per period "
                f"({abs(round(relative_slope, 1))}% of mean). "
                f"The trend explains {round(r_squared * 100, 1)}% of the variation."
            ),
        }


    def _growth_analysis(self, series: pd.Series) -> Dict:
        """
        Calculate period-over-period growth rates.

        This is the MOST IMPORTANT metric in business reports.
        "Revenue grew 15% MoM" — every executive wants to hear this.
        """

        pct_change = series.pct_change().dropna()

        if len(pct_change) == 0:
            return {}

        # Replace inf values (division by zero when previous period was 0)
        pct_change = pct_change.replace([np.inf, -np.inf], np.nan).dropna()

        if len(pct_change) == 0:
            return {}

        growth_rates = (pct_change * 100).round(2)

        # CAGR (Compound Annual Growth Rate) if enough data
        cagr = None
        if len(series) >= 4:
            first_val = series.iloc[0]
            last_val = series.iloc[-1]
            n_periods = len(series) - 1
            if first_val > 0 and last_val > 0:
                cagr = round(
                    (((last_val / first_val) ** (1 / n_periods)) - 1) * 100, 2
                )

        # Growth streak analysis
        positive_streaks, negative_streaks = self._calculate_streaks(pct_change)

        return {
            "period_growth_rates": {
                "dates": growth_rates.index.strftime('%Y-%m-%d').tolist(),
                "rates": growth_rates.values.tolist(),
            },
            "avg_growth_rate": round(float(growth_rates.mean()), 2),
            "median_growth_rate": round(float(growth_rates.median()), 2),
            "latest_growth_rate": round(float(growth_rates.iloc[-1]), 2),
            "max_growth": {
                "rate": round(float(growth_rates.max()), 2),
                "period": str(growth_rates.idxmax().strftime('%Y-%m-%d')),
            },
            "max_decline": {
                "rate": round(float(growth_rates.min()), 2),
                "period": str(growth_rates.idxmin().strftime('%Y-%m-%d')),
            },
            "positive_periods": int((growth_rates > 0).sum()),
            "negative_periods": int((growth_rates < 0).sum()),
            "volatility": round(float(growth_rates.std()), 2),
            "cagr": cagr,
            "current_streak": positive_streaks if positive_streaks > 0 else -negative_streaks,
            "interpretation": self._growth_interpretation(growth_rates, cagr),
        }


    def _calculate_streaks(self, pct_change: pd.Series) -> Tuple[int, int]:
        """Count consecutive positive/negative growth periods from latest"""

        positive_streak = 0
        negative_streak = 0

        for val in pct_change.iloc[::-1]:
            if val > 0:
                if negative_streak > 0:
                    break
                positive_streak += 1
            elif val < 0:
                if positive_streak > 0:
                    break
                negative_streak += 1
            else:
                break

        return positive_streak, negative_streak


    def _growth_interpretation(self, growth_rates: pd.Series,
                                cagr: Optional[float]) -> str:
        """Generate human-readable growth interpretation"""

        latest = growth_rates.iloc[-1]
        avg = growth_rates.mean()

        parts = []

        # Latest growth
        if latest > 0:
            parts.append(
                f"The most recent period showed **{latest:.1f}% growth**."
            )
        elif latest < 0:
            parts.append(
                f"The most recent period showed a **{abs(latest):.1f}% decline**."
            )
        else:
            parts.append("The most recent period was flat (0% change).")

        # Average growth
        if avg > 0:
            parts.append(f"Average growth rate across all periods: **{avg:.1f}%**.")
        else:
            parts.append(f"Average decline across all periods: **{abs(avg):.1f}%**.")

        # Volatility
        vol = growth_rates.std()
        if vol > 20:
            parts.append("Growth is **highly volatile** — large swings between periods.")
        elif vol > 10:
            parts.append("Growth shows **moderate volatility**.")
        else:
            parts.append("Growth is **relatively stable** and predictable.")

        # CAGR
        if cagr is not None:
            parts.append(f"Compound growth rate (CAGR): **{cagr:.1f}%** per period.")

        return " ".join(parts)


    def _period_comparison(self, series: pd.Series) -> Dict:
        """
        Compare latest period vs previous period.

        This is THE comparison every manager asks about:
        "How did this month compare to last month?"
        """

        if len(series) < 2:
            return {"available": False}

        current = series.iloc[-1]
        previous = series.iloc[-2]

        if previous != 0:
            change_pct = ((current - previous) / previous) * 100
        else:
            change_pct = 0

        change_abs = current - previous

        # Determine direction and emoji
        if change_pct > 5:
            direction = "increased"
            emoji = "🟢"
        elif change_pct < -5:
            direction = "decreased"
            emoji = "🔴"
        else:
            direction = "remained stable"
            emoji = "🟡"

        result = {
            "available": True,
            "current_period": {
                "date": str(series.index[-1].strftime('%Y-%m-%d')),
                "value": round(float(current), 2),
            },
            "previous_period": {
                "date": str(series.index[-2].strftime('%Y-%m-%d')),
                "value": round(float(previous), 2),
            },
            "change_absolute": round(float(change_abs), 2),
            "change_percentage": round(float(change_pct), 2),
            "direction": direction,
            "emoji": emoji,
            "interpretation": (
                f"{emoji} {series.name or 'Value'} {direction} from "
                f"**{previous:,.2f}** to **{current:,.2f}** "
                f"({'+' if change_pct > 0 else ''}{change_pct:.1f}%, "
                f"{'+' if change_abs > 0 else ''}{change_abs:,.2f} absolute change)."
            ),
        }

        # Also compare to 3 periods ago (if available)
        if len(series) >= 4:
            three_ago = series.iloc[-4]
            if three_ago != 0:
                change_3p = ((current - three_ago) / three_ago) * 100
                result["vs_3_periods_ago"] = {
                    "value": round(float(three_ago), 2),
                    "change_pct": round(float(change_3p), 2),
                }

        return result


    def _best_worst_periods(self, series: pd.Series) -> Dict:
        """Identify best and worst performing periods"""

        return {
            "best_period": {
                "date": str(series.idxmax().strftime('%Y-%m-%d')),
                "value": round(float(series.max()), 2),
                "vs_average": round(
                    float(((series.max() - series.mean()) / series.mean()) * 100), 1
                ) if series.mean() != 0 else 0,
            },
            "worst_period": {
                "date": str(series.idxmin().strftime('%Y-%m-%d')),
                "value": round(float(series.min()), 2),
                "vs_average": round(
                    float(((series.min() - series.mean()) / series.mean()) * 100), 1
                ) if series.mean() != 0 else 0,
            },
            "average": round(float(series.mean()), 2),
            "range": round(float(series.max() - series.min()), 2),
        }


    def _moving_averages(self, series: pd.Series) -> Dict:
        """
        Calculate moving averages for trend smoothing.

        WHY MOVING AVERAGES?
        Raw data is noisy. Moving averages smooth out fluctuations
        and reveal the TRUE underlying trend.

        Used in charts: raw line + smooth MA line overlaid.
        """

        ma_data = {}

        # Short-term MA (3-period)
        if len(series) >= 3:
            ma3 = series.rolling(window=3, min_periods=1).mean()
            ma_data["ma_3"] = {
                "label": "3-Period Moving Avg",
                "dates": ma3.index.strftime('%Y-%m-%d').tolist(),
                "values": ma3.round(2).values.tolist(),
            }

        # Medium-term MA (6-period)
        if len(series) >= 6:
            ma6 = series.rolling(window=6, min_periods=1).mean()
            ma_data["ma_6"] = {
                "label": "6-Period Moving Avg",
                "dates": ma6.index.strftime('%Y-%m-%d').tolist(),
                "values": ma6.round(2).values.tolist(),
            }

        return ma_data


    def _momentum_analysis(self, series: pd.Series) -> Dict:
        """
        Is growth accelerating or decelerating?

        MOMENTUM = change in growth rate
        - Accelerating: growth rate is increasing each period
        - Decelerating: growth rate is decreasing (still positive, but slowing)
        - Reversing: switching from growth to decline or vice versa

        WHY THIS MATTERS:
        A company growing at 20%, then 15%, then 10% is DECELERATING
        even though it's still growing. Executives need to know this.
        """

        if len(series) < 4:
            return {"available": False}

        pct_change = series.pct_change().dropna()
        pct_change = pct_change.replace([np.inf, -np.inf], np.nan).dropna()

        if len(pct_change) < 3:
            return {"available": False}

        # Momentum = change in growth rate
        growth_acceleration = pct_change.diff().dropna()

        # Recent momentum (last 3 periods)
        recent_momentum = growth_acceleration.tail(3).mean()

        if recent_momentum > 0.02:
            status = "accelerating"
            emoji = "🚀"
            description = "Growth is speeding up — each period grows faster than the last"
        elif recent_momentum < -0.02:
            status = "decelerating"
            emoji = "⚠️"
            description = "Growth is slowing down — still positive but losing momentum"
        else:
            status = "steady"
            emoji = "➡️"
            description = "Growth rate is consistent across recent periods"

        return {
            "available": True,
            "status": status,
            "emoji": emoji,
            "description": description,
            "recent_momentum": round(float(recent_momentum * 100), 2),
        }


    def _seasonality_check(self, series: pd.Series, freq: str) -> Dict:
        """
        Detect seasonal patterns in the data.

        METHOD:
        1. Group data by month (or quarter)
        2. Calculate average for each month
        3. If coefficient of variation is high → seasonality exists
        4. Identify peak and trough months

        EXAMPLE OUTPUT:
        "Revenue peaks in December (holiday season) and dips in
         February. Seasonal variation accounts for ~25% of fluctuation."
        """

        if freq not in ['M', 'W', 'D'] or len(series) < 12:
            return {
                "detected": False,
                "reason": "Need at least 12 monthly data points to detect seasonality"
            }

        # Group by month
        monthly_avg = series.groupby(series.index.month).mean()

        # Coefficient of variation
        if monthly_avg.mean() == 0:
            return {"detected": False, "reason": "All values are zero"}

        cv = monthly_avg.std() / monthly_avg.mean()

        month_names = [
            '', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
        ]

        peak_month = int(monthly_avg.idxmax())
        trough_month = int(monthly_avg.idxmin())

        detected = cv > 0.15    # threshold for "meaningful" seasonality

        return {
            "detected": detected,
            "coefficient_of_variation": round(float(cv), 3),
            "peak_month": {
                "month_number": peak_month,
                "month_name": month_names[peak_month],
                "average_value": round(float(monthly_avg.max()), 2),
            },
            "trough_month": {
                "month_number": trough_month,
                "month_name": month_names[trough_month],
                "average_value": round(float(monthly_avg.min()), 2),
            },
            "monthly_pattern": {
                month_names[int(m)]: round(float(v), 2)
                for m, v in monthly_avg.items()
                if int(m) <= 12
            },
            "interpretation": (
                f"{'Strong seasonal pattern detected' if detected else 'No significant seasonality'}. "
                f"Peak month: **{month_names[peak_month]}** "
                f"(avg: {monthly_avg.max():,.0f}), "
                f"lowest month: **{month_names[trough_month]}** "
                f"(avg: {monthly_avg.min():,.0f}). "
                f"Seasonal variation: {cv:.1%}."
            ) if detected else "No significant seasonal pattern detected in the data."
        }


    def _secondary_trends(self, df: pd.DataFrame,
                           date_col: str,
                           other_cols: List[str],
                           freq: str) -> Dict:
        """
        Quick trend summary for other numeric columns.

        WHY?
        If the primary metric is Revenue, the report might also
        want to mention trends in Cost, Quantity, Profit.
        """

        secondary = {}

        for col in other_cols:
            try:
                ts = self._prepare_time_series(df, date_col, col, freq)
                if ts is not None and len(ts) >= 3:
                    trend = self._overall_trend(ts)
                    pct_change = ts.pct_change().dropna()
                    pct_change = pct_change.replace(
                        [np.inf, -np.inf], np.nan
                    ).dropna()

                    secondary[col] = {
                        "direction": trend["direction"],
                        "emoji": trend["emoji"],
                        "avg_growth": round(
                            float(pct_change.mean() * 100), 2
                        ) if len(pct_change) > 0 else 0,
                        "latest_value": round(float(ts.iloc[-1]), 2),
                        "total": round(float(ts.sum()), 2),
                    }
            except Exception as e:
                logger.warning(f"Error analyzing secondary trend for {col}: {e}")

        return secondary


    # ═══════════════════════════════════════════════════════
    # UTILITY METHODS
    # ═══════════════════════════════════════════════════════

    def _series_to_dict(self, series: pd.Series) -> Dict:
        """Convert time series to JSON-serializable dict"""
        return {
            "dates": series.index.strftime('%Y-%m-%d').tolist(),
            "values": series.round(2).values.tolist(),
            "column_name": series.name or "value",
        }