# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/ingestion/data_loader.py

"""
DATA LOADER MODULE
──────────────────
Handles loading data from multiple file formats.

DESIGN DECISIONS:
1. Supports both file paths (for scripts) and uploaded files (for Streamlit)
2. Auto-detects and parses date columns
3. Handles common encoding issues
4. Returns a clean DataFrame ready for analysis

WHY a separate class instead of just pd.read_csv()?
- Encapsulation: All loading logic in one place
- Reusability: Same loader works for CSV, Excel, and later SQL
- Error handling: Graceful failures with clear messages
- Auto-parsing: Dates auto-detected without user input
"""

import pandas as pd
from typing import Optional, Union
from pathlib import Path
from src.utils.logger import logger


class DataLoader:
    """
    Loads tabular data from various sources.

    Usage:
        loader = DataLoader()

        # From file path
        df = loader.load(file_path="data/sales.csv")

        # From Streamlit upload
        df = loader.load(uploaded_file=st_uploaded_file)
    """

    SUPPORTED_FORMATS = {'.csv', '.xlsx', '.xls'}

    def load(self,
             file_path: Optional[str] = None,
             uploaded_file=None) -> pd.DataFrame:
        """
        Load data from either a file path or Streamlit uploaded file.

        Parameters:
        -----------
        file_path : str, optional
            Path to a local file
        uploaded_file : UploadedFile, optional
            Streamlit's uploaded file object

        Returns:
        --------
        pd.DataFrame : Cleaned and date-parsed DataFrame

        Raises:
        -------
        ValueError : If format is unsupported or no input provided
        """

        # Validate input — must provide one or the other
        if file_path is None and uploaded_file is None:
            raise ValueError("Provide either 'file_path' or 'uploaded_file'")

        # ── Load from Streamlit Upload ──────────────────
        if uploaded_file is not None:
            file_name = uploaded_file.name
            logger.info(f"Loading uploaded file: {file_name}")
            df = self._load_by_extension(file_name, uploaded_file)

        # ── Load from File Path ─────────────────────────
        else:
            file_name = file_path
            logger.info(f"Loading file: {file_path}")

            # Check file exists
            if not Path(file_path).exists():
                raise FileNotFoundError(f"File not found: {file_path}")

            df = self._load_by_extension(file_name, file_path)

        # ── Post-processing ─────────────────────────────
        df = self._parse_dates(df)
        df = self._clean_column_names(df)
        df = self._basic_cleaning(df)

        logger.info(f"Loaded successfully: {df.shape[0]} rows × {df.shape[1]} columns")

        return df


    def _load_by_extension(self, file_name: str, source) -> pd.DataFrame:
        """Route to correct pandas reader based on file extension"""

        ext = Path(file_name).suffix.lower()

        if ext not in self.SUPPORTED_FORMATS:
            raise ValueError(
                f"Unsupported format: '{ext}'. "
                f"Supported: {self.SUPPORTED_FORMATS}"
            )

        if ext == '.csv':
            # Try UTF-8 first, fall back to latin-1
            # WHY? Some CSVs from Excel use latin-1 encoding
            try:
                return pd.read_csv(source, encoding='utf-8')
            except UnicodeDecodeError:
                logger.warning("UTF-8 failed, trying latin-1 encoding")
                return pd.read_csv(source, encoding='latin-1')

        elif ext in ('.xlsx', '.xls'):
            return pd.read_excel(source, engine='openpyxl')


    def _parse_dates(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Auto-detect and convert date columns.

        HOW IT WORKS:
        1. Check column names for date-like words
        2. Try to parse object columns as dates
        3. Only convert if >80% of values parse successfully

        WHY auto-detect?
        The user shouldn't have to tell us which column is a date.
        A smart tool figures it out automatically.
        """

        date_keywords = ['date', 'time', 'datetime', 'timestamp',
                         'created', 'updated', 'month', 'year']

        for col in df.columns:
            col_lower = col.lower().strip()

            # Strategy 1: Column name contains date-related keyword
            if any(keyword in col_lower for keyword in date_keywords):
                try:
                    df[col] = pd.to_datetime(df[col], infer_datetime_format=True)
                    logger.info(f"Parsed '{col}' as datetime (name match)")
                    continue
                except (ValueError, TypeError):
                    pass

            # Strategy 2: Object column that looks like dates
            if df[col].dtype == 'object':
                try:
                    # Try parsing a sample first (faster than parsing all)
                    sample = df[col].dropna().head(20)
                    parsed = pd.to_datetime(sample, infer_datetime_format=True)

                    # If >80% parsed successfully, convert the whole column
                    success_rate = len(parsed.dropna()) / len(sample)
                    if success_rate > 0.8:
                        df[col] = pd.to_datetime(df[col],
                                                  infer_datetime_format=True,
                                                  errors='coerce')  # invalid → NaT
                        logger.info(f"Parsed '{col}' as datetime (auto-detect)")
                except (ValueError, TypeError):
                    pass

        return df


    def _clean_column_names(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Standardize column names.

        'Total Revenue ($)' → 'total_revenue'
        'Customer Name   '  → 'customer_name'

        WHY?
        Clean column names prevent bugs and make code cleaner.
        df['Total Revenue ($)'] is error-prone
        df['total_revenue'] is reliable
        """

        df.columns = (
            df.columns
            .str.strip()                          # remove whitespace
            .str.lower()                          # lowercase
            .str.replace(r'[^\w\s]', '', regex=True)  # remove special chars
            .str.replace(r'\s+', '_', regex=True)     # spaces → underscores
        )

        return df


    def _basic_cleaning(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Basic data cleaning.

        NOTE: We do MINIMAL cleaning here — just enough to not break analysis.
        We don't drop rows or impute values (that's a business decision).
        We just flag issues.
        """

        # Remove completely empty rows (if any)
        initial_rows = len(df)
        df = df.dropna(how='all')  # only drop if ALL columns are NaN
        dropped = initial_rows - len(df)
        if dropped > 0:
            logger.warning(f"Dropped {dropped} completely empty rows")

        # Remove duplicate rows
        dupes = df.duplicated().sum()
        if dupes > 0:
            logger.warning(f"Found {dupes} duplicate rows (keeping them for now)")

        return df