# -*- coding: utf-8 -*-
"""data_profiler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDpuPwLfziKJexX-KyhBxzRVIUoiWwm
"""

# src/ingestion/data_profiler.py

"""
DATA PROFILER MODULE
────────────────────
Creates a comprehensive "profile" of the uploaded dataset.

PURPOSE:
This profile gets fed to the LLM later so it understands
what kind of data it's working with WITHOUT seeing all rows.

Think of it as a "data resume" — tells the LLM:
- How many rows/columns
- What types of data
- What the value ranges are
- Where the problems are (nulls, outliers)
- What time period the data covers
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional
from src.utils.logger import logger


class DataProfiler:
    """
    Generates a structured profile of any DataFrame.

    This profile serves two purposes:
    1. Shown to USER in Streamlit (data understanding)
    2. Sent to LLM as context (so it writes accurate reports)
    """

    def profile(self, df: pd.DataFrame) -> Dict:
        """
        Generate a comprehensive data profile.

        Parameters:
        -----------
        df : pd.DataFrame
            The dataset to profile

        Returns:
        --------
        Dict with sections:
            - overview: row count, column count, memory
            - columns: detailed info per column
            - date_range: start/end dates (if date column exists)
            - quality: missing values, duplicates
            - numeric_summary: stats for number columns
            - categorical_summary: value counts for text columns
        """

        logger.info("Starting data profiling...")

        profile = {
            "overview": self._overview(df),
            "columns": self._column_details(df),
            "date_info": self._date_info(df),
            "quality": self._quality_check(df),
            "numeric_summary": self._numeric_summary(df),
            "categorical_summary": self._categorical_summary(df),
        }

        logger.info("Data profiling complete")
        return profile


    def _overview(self, df: pd.DataFrame) -> Dict:
        """High-level dataset overview"""
        return {
            "total_rows": int(df.shape[0]),
            "total_columns": int(df.shape[1]),
            "memory_mb": round(df.memory_usage(deep=True).sum() / 1024 / 1024, 2),
            "numeric_columns": int(len(df.select_dtypes(include=[np.number]).columns)),
            "categorical_columns": int(len(df.select_dtypes(include=['object', 'category']).columns)),
            "datetime_columns": int(len(df.select_dtypes(include=['datetime64']).columns)),
            "duplicate_rows": int(df.duplicated().sum()),
        }


    def _column_details(self, df: pd.DataFrame) -> Dict:
        """Detailed information for each column"""
        columns = {}

        for col in df.columns:
            col_info = {
                "dtype": str(df[col].dtype),
                "non_null_count": int(df[col].notna().sum()),
                "null_count": int(df[col].isnull().sum()),
                "null_percentage": round(df[col].isnull().mean() * 100, 1),
                "unique_values": int(df[col].nunique()),
                "sample_values": [str(v) for v in df[col].dropna().head(3).tolist()],
            }

            # Add numeric-specific info
            if pd.api.types.is_numeric_dtype(df[col]):
                col_info.update({
                    "min": round(float(df[col].min()), 2),
                    "max": round(float(df[col].max()), 2),
                    "mean": round(float(df[col].mean()), 2),
                    "median": round(float(df[col].median()), 2),
                })

            # Add categorical-specific info
            if df[col].dtype == 'object':
                top_values = df[col].value_counts().head(5)
                col_info["top_values"] = {
                    str(k): int(v) for k, v in top_values.items()
                }

            columns[col] = col_info

        return columns


    def _date_info(self, df: pd.DataFrame) -> Optional[Dict]:
        """Extract date range information"""
        date_cols = df.select_dtypes(include=['datetime64']).columns

        if len(date_cols) == 0:
            return None

        # Use the first date column found
        date_col = date_cols[0]

        return {
            "date_column": date_col,
            "start_date": str(df[date_col].min().date()),
            "end_date": str(df[date_col].max().date()),
            "total_days": int((df[date_col].max() - df[date_col].min()).days),
            "records_per_month": (
                df.set_index(date_col)
                .resample('M')
                .size()
                .to_dict()
            ) if len(df) > 0 else {},
        }


    def _quality_check(self, df: pd.DataFrame) -> Dict:
        """Data quality assessment"""

        # Missing values per column
        missing = df.isnull().sum()
        missing_cols = missing[missing > 0].to_dict()

        # Calculate overall quality score (0-100)
        total_cells = df.shape[0] * df.shape[1]
        total_missing = df.isnull().sum().sum()
        completeness = round((1 - total_missing / total_cells) * 100, 1) if total_cells > 0 else 100

        return {
            "completeness_score": completeness,
            "total_missing_values": int(total_missing),
            "columns_with_missing": {
                col: {
                    "count": int(count),
                    "percentage": round(count / len(df) * 100, 1)
                }
                for col, count in missing_cols.items()
            },
            "duplicate_rows": int(df.duplicated().sum()),
            "quality_rating": (
                "Excellent" if completeness >= 98
                else "Good" if completeness >= 95
                else "Fair" if completeness >= 90
                else "Poor"
            ),
        }


    def _numeric_summary(self, df: pd.DataFrame) -> Dict:
        """Statistical summary of numeric columns"""
        numeric_df = df.select_dtypes(include=[np.number])

        if numeric_df.empty:
            return {}

        summary = {}
        for col in numeric_df.columns:
            series = numeric_df[col].dropna()
            summary[col] = {
                "count": int(len(series)),
                "mean": round(float(series.mean()), 2),
                "std": round(float(series.std()), 2),
                "min": round(float(series.min()), 2),
                "25%": round(float(series.quantile(0.25)), 2),
                "50%": round(float(series.median()), 2),
                "75%": round(float(series.quantile(0.75)), 2),
                "max": round(float(series.max()), 2),
            }

        return summary


    def _categorical_summary(self, df: pd.DataFrame) -> Dict:
        """Summary of categorical columns"""
        cat_df = df.select_dtypes(include=['object', 'category'])

        if cat_df.empty:
            return {}

        summary = {}
        for col in cat_df.columns:
            value_counts = df[col].value_counts()
            summary[col] = {
                "unique_count": int(df[col].nunique()),
                "most_common": str(value_counts.index[0]) if len(value_counts) > 0 else None,
                "most_common_count": int(value_counts.iloc[0]) if len(value_counts) > 0 else 0,
                "least_common": str(value_counts.index[-1]) if len(value_counts) > 0 else None,
                "distribution": {
                    str(k): int(v) for k, v in value_counts.head(10).items()
                },
            }

        return summary


    def get_llm_context(self, profile: Dict) -> str:
        """
        Convert profile to a text summary for LLM consumption.

        WHY?
        The LLM can't read Python dicts efficiently.
        A well-formatted text summary helps it write better reports.
        This is PROMPT ENGINEERING in action.
        """

        overview = profile["overview"]
        quality = profile["quality"]

        context = f"""
DATASET OVERVIEW:
- Total Records: {overview['total_rows']:,}
- Total Columns: {overview['total_columns']}
- Numeric Columns: {overview['numeric_columns']}
- Categorical Columns: {overview['categorical_columns']}
- Data Quality Score: {quality['completeness_score']}% ({quality['quality_rating']})
- Missing Values: {quality['total_missing_values']} total
"""

        # Add date range if available
        if profile["date_info"]:
            date_info = profile["date_info"]
            context += f"""
TIME PERIOD:
- Date Column: {date_info['date_column']}
- From: {date_info['start_date']}
- To: {date_info['end_date']}
- Span: {date_info['total_days']} days
"""

        # Add numeric column summaries
        if profile["numeric_summary"]:
            context += "\nNUMERIC COLUMNS:\n"
            for col, stats in profile["numeric_summary"].items():
                context += (f"- {col}: mean={stats['mean']}, "
                          f"min={stats['min']}, max={stats['max']}, "
                          f"std={stats['std']}\n")

        # Add categorical column summaries
        if profile["categorical_summary"]:
            context += "\nCATEGORICAL COLUMNS:\n"
            for col, info in profile["categorical_summary"].items():
                context += (f"- {col}: {info['unique_count']} unique values, "
                          f"most common = '{info['most_common']}'\n")

        return context.strip()