OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyBtPNDkNymciQkaLYWfFo-Vb308M_TyIHk"
